### ISSUE TITLE
netrc FileNotFoundError for private PyPI server

### ISSUE THREAD

**Issue by danielgafni** [nix-community/poetry2nix#1244]
### Describe the issue
Hello!

There is a weird error I'm getting when trying to use the `netrc` file to access a private PyPI server:

```python
Traceback (most recent call last):
  File "/nix/store/ipfjy7lra1hdl6yrpfidsjip4rndmlz1-fetch_from_legacy.py", line 50, in <module>
    netrc_obj = netrc.netrc(os.environ["NETRC"])
  File "/nix/store/95cxzy2hpizr23343b8bskl4yacf4b3l-python3-3.10.11/lib/python3.10/netrc.py", line 30, in __init__
    with open(file, encoding="utf-8") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/nix/.netrc'
```

The file clearly exists (and has correct permissions according to this [readme](https://github.com/rskew/poetry2nix-private-pypi-demo)). 
The command I'm running is:
```shell
 nix-shell -I NETRC=/etc/nix/.netrc --option extra-sandbox-paths /etc/nix
```
I realize the issue is probably not with `poetry2nix`, but I'm not sure how to proceed further... 

### Additional context

`default.nix`/`shell.nix`/`flake.nix`:
```nix
{ pkgs ? import <nixpkgs> {} }:
let
  myAppEnv = pkgs.poetry2nix.mkPoetryEnv {
    python=pkgs.python310;
    projectDir = ./.;
    preferWheels = true;
    editablePackageSources = {
      my-app = ./my_app;
    };
    overrides = pkgs.poetry2nix.defaultPoetryOverrides.extend
                (self: super: {
                  wave = super.wave.overridePythonAttrs (old: {
                    nativeBuildInputs = (old.nativeBuildInputs or [ ])
                      ++ [ self.setuptools ];
                  });
                });

  };
in myAppEnv.env.overrideAttrs (oldAttrs: {
  buildInputs = [ pkgs.python310Packages.wheel pkgs.python310Packages.setuptools ];
})

```

**Comment by danielgafni** [comment]
Setting `POETRY_HTTP_BASIC_...` environment variables helped. Doesn't seem like the `.netrc` file is needed at all?

**Comment by pcboy** [comment]
@danielgafni How did you exactly set these POETRY_HTTP_BASIC_ env variables? My understanding is that you would need impureEnvVars to do something like this.

**Comment by malteneuss** [comment]
@danielgafni 
I'm also interested in you Poetry http auth setup. Does poetry2nix use the `POETRY_HTTP_BASIC_...` config at all? I would assume it extracts the paths from the `poetry.lock` and uses its [custom fetch implementation](https://github.com/nix-community/poetry2nix/blob/3c92540611f42d3fb2d0d084a6c694cd6544b609/vendor/pyproject.nix/fetchers/fetch-from-legacy.py) to download the packages (without using Poetry).

**Comment by danielgafni** [comment]
Hey @malteneuss ! 

Actually, I didn't proceed with `poetry2nix` at that time due to other issues. I don't remember if setting these env vars actually helped or not. It's quite possible it didn't. I didn't have good `nix` understanding at that time.

I'll try to get back to this soon.

**Comment by malteneuss** [comment]
If anyone is interested, i wrote up the current way to use credentials for a private repository using NETRC. I think this is the only supported way: https://github.com/nix-community/poetry2nix/pull/1600

**Comment by danielgafni** [comment]
Hey @malteneuss, looks amazing! Will try it out. 

This is how hours of time saved looks like :)

**Comment by mcamp-ata** [comment]
> If anyone is interested, i wrote up the current way to use credentials for a private repository using NETRC. I think this is the only supported way: #1600

I just tried doing this an maybe I'm an idiot but I couldn't get it to work.

```
machine https://myartifactory.jfrog.io/artifactory/api/pypi/my-pypi/
login mcamp@ata-llc.com
password myartifactorytoken1234556977
```

put at `/etc/nix/netrc` set to `0600`.

My `/etc/nix/conf.nix` looks like:

```
# WARNING: this file is generated from the nix.* options in
# your NixOS configuration, typically
# /etc/nixos/configuration.nix.  Do not edit it!
allowed-users = root abe
auto-optimise-store = true
builders = 
cores = 0
experimental-features = nix-command flakes
fallback = true
http-connections = 50
log-lines = 50
max-jobs = auto
require-sigs = true
sandbox = relaxed
sandbox-fallback = false
substituters = https://cache.nixos.org/ https://nix-gaming.cachix.org https://cache.nixos.org/
system-features = nixos-test benchmark big-parallel kvm
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= public:QUkZTErD8fx9HQ64kuuEUZHO9tXNzws7chV8qy/KLUk= nix-gaming.cachix.org-1:nbjlureqMbRAxR1gJ/f3hxemL9svXaZF/Ees8vCUUs4=
trusted-substituters = 
trusted-users = root abe @ldap_user
warn-dirty = false
extra-sandbox-paths = /etc/nix/netrc
extra-experimental-features = nix-command flakes
```

But when I try to build my derivation that builds a `poetry2nix` Python environment that requires a package from a private Artifactory, I get a `401`. 

```
error: builder for '/nix/store/7y3ak0jk30s3kxv5zhf17rgb5qqn427y-flink_utils-0.1.0-py3-none-any.whl.drv' failed with exit code 1;
       last 23 log lines:
       > Reading index https://myartifactory.jfrog.io/artifactory/api/pypi/my-pypi/
       > Traceback (most recent call last):
       >   File "/nix/store/0rzh74dywg10ggl3ds6khsdpc84nbp96-fetch-from-legacy.py", line 82, in <module>
       >     response = urllib.request.urlopen(req, context=context)
       >                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/8dzgagiwp6xi6hahsdgq6y4kb5v8kn4j-python3-3.11.8/lib/python3.11/urllib/request.py", line 216, in urlopen
       >     return opener.open(url, data, timeout)
       >            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/8dzgagiwp6xi6hahsdgq6y4kb5v8kn4j-python3-3.11.8/lib/python3.11/urllib/request.py", line 525, in open
       >     response = meth(req, response)
       >                ^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/8dzgagiwp6xi6hahsdgq6y4kb5v8kn4j-python3-3.11.8/lib/python3.11/urllib/request.py", line 634, in http_response
       >     response = self.parent.error(
       >                ^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/8dzgagiwp6xi6hahsdgq6y4kb5v8kn4j-python3-3.11.8/lib/python3.11/urllib/request.py", line 563, in error
       >     return self._call_chain(*args)
       >            ^^^^^^^^^^^^^^^^^^^^^^^
       >   File "/nix/store/8dzgagiwp6xi6hahsdgq6y4kb5v8kn4j-python3-3.11.8/lib/python3.11/urllib/request.py", line 496, in _call_chain
       >     result = func(*args)
       >              ^^^^^^^^^^^
       >   File "/nix/store/8dzgagiwp6xi6hahsdgq6y4kb5v8kn4j-python3-3.11.8/lib/python3.11/urllib/request.py", line 643, in http_error_default
       >     raise HTTPError(req.full_url, code, msg, hdrs, fp)
       > urllib.error.HTTPError: HTTP Error 401:
       For full logs, run 'nix log /nix/store/7y3ak0jk30s3kxv5zhf17rgb5qqn427y-flink_utils-0.1.0-py3-none-any.whl.drv'.
error: 1 dependencies of derivation '/nix/store/17aiwh3alqcc12x2vg43ydjw75p8gal8-python3.9-flink-utils-0.1.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rc3686hmxkp09wyqc259px6q1yfmj9hd-python3-3.9.19-env.drv' failed to build
error: 1 dependencies of derivation '/nix/store/jkkyv83iy6980b1nwflvxqhwb5z8sizn-flink-job-boat-model.drv' failed to build
```

my `pyproject.toml`:

```
[tool.poetry]
name = "boat-model"
version = "0.1.0"
description = ""
authors = ["Matt Camp <mcamp@ata-llc.com>"]
readme = "README.md"

[[tool.poetry.source]]
name = "jfrog"
url = "https://myartifactory.jfrog.io/artifactory/api/pypi/my-pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
kafka-python = "^2.0.2"
schema = "^0.7.5"
python-dateutil = "^2.9.0.post0"
simplejson = "^3.19.2"
confluent-kafka = "^2.3.0"
pytest = "^8.1.1"
google-api-python-client = "^2.124.0"
boto3 = "^1.34.75"
pillow = "^10.3.0"
apache-flink = "^1.18.0"
apache-flink-libraries = "^1.18.0"
psycopg = { extras = ["binary"], version = "^3.1.18" }
flink-utils = "^0.1.0" 

[tool.poetry.group.dev.dependencies]
pytest-mock = "^3.14.0"
bpython = "^0.24"
pytest = "^8.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

**Comment by mcamp-ata** [comment]
> @mcamp-ata Could you try [NixOS/nix#6115](https://github.com/NixOS/nix/issues/6115) to see if the extra-sandbox-paths are being ignored?


This seemed to work:

```
╰─ cat $(nix-build --extra-sandbox-paths /tmp/sandbox-file)
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /nix/store/n2zby5jx8lpbcxhg5ln3zfarsjh8xv5p-nix-sandbox-test
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ TEST
```


> Are you using NixOS and flakes? Then the nix-daemon has to get this NETRC file path (as seen in the poetry2nix README).

I am using NixOS and flakes and best I can tell the `nix-daemon` has the NETRC file path:

```
───────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /etc/systemd/system/nix-daemon.service.d/overrides.conf
───────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ [Unit]
   2   │ RequiresMountsFor=/nix/store
   3   │ X-Restart-Triggers=/nix/store/5jri9ppvhxwq948sgili0x9vbk1z033n-X-Restart-Triggers-nix-daemon
   4   │ 
   5   │ [Service]
   6   │ Environment="CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt"
   7   │ Environment="LOCALE_ARCHIVE=/nix/store/naa6s54b4hc55740lblbs9phv7xk317h-glibc-locales-2.39-52/lib/locale/locale-a
       │ rchive"
   8   │ Environment="PATH=/nix/store/j7rp0y3ii1w3dlbflbxlv4g7hbaaz3bs-nix-2.18.2/bin:/nix/store/96n916fc8kvkrj48dsmmqmdwk
       │ 9c9r0lq-util-linux-2.40.1-bin/bin:/nix/store/0g1s8yd0biawp32fl3i7kdbi219jx6aq-openssh-9.7p1/bin:/nix/store/php4qi
       │ dg2bxzmm79vpri025bqi0fa889-coreutils-9.5/bin:/nix/store/jjcsr5gs4qanf7ln5c6wgcq4sn75a978-findutils-4.9.0/bin:/nix
       │ /store/28gpmx3z6ss3znd7fhmrzmvk3x5lnfbk-gnugrep-3.11/bin:/nix/store/5zjms21vpxlkbc0qyl5pmj2sidfmzmd7-gnused-4.9/b
       │ in:/nix/store/xjiifrz7ha6s29gp0p0j3w0155phxmia-systemd-255.6/bin:/nix/store/j7rp0y3ii1w3dlbflbxlv4g7hbaaz3bs-nix-
       │ 2.18.2/sbin:/nix/store/96n916fc8kvkrj48dsmmqmdwk9c9r0lq-util-linux-2.40.1-bin/sbin:/nix/store/0g1s8yd0biawp32fl3i
       │ 7kdbi219jx6aq-openssh-9.7p1/sbin:/nix/store/php4qidg2bxzmm79vpri025bqi0fa889-coreutils-9.5/sbin:/nix/store/jjcsr5
       │ gs4qanf7ln5c6wgcq4sn75a978-findutils-4.9.0/sbin:/nix/store/28gpmx3z6ss3znd7fhmrzmvk3x5lnfbk-gnugrep-3.11/sbin:/ni
       │ x/store/5zjms21vpxlkbc0qyl5pmj2sidfmzmd7-gnused-4.9/sbin:/nix/store/xjiifrz7ha6s29gp0p0j3w0155phxmia-systemd-255.
       │ 6/sbin"
   9   │ Environment="TZDIR=/nix/store/y6hmqbmbwq0rmx1fzix5c5jszla2pzmp-tzdata-2024a/share/zoneinfo"
  10   │ X-StopIfChanged=false
  11   │ CPUSchedulingPolicy=other
  12   │ Environment=NETRC=/etc/nix/netrc
  13   │ IOSchedulingClass=best-effort
  14   │ IOSchedulingPriority=4
  15   │ LimitNOFILE=1048576
```

**Comment by malteneuss** [comment]
hm, then i'm out of ideas. I would try to connect via poetry (without Nix) using the same NETRC file in `~/.netrc` to make sure the authentication works at all. Then try poetry2nix with a minimal `pyproject.toml` with a single dependency with pinned source, and with a single primary repository entry like

```toml
[[tool.poetry.source]]
name = "jfrog"
url = "https://myartifactory.jfrog.io/artifactory/api/pypi/my-pypi/simple"
priority = "primary"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
kafka-python = { version = "^2.0.2", source = "jfrog"}
```

**Comment by mcamp-ata** [comment]
So good news.. I was able to get this to work finally.. on a different machine and I haven't reproduced it yet. 

This is what I did... 

1. Put the `netrc` file at `/etc/netrc` **NOT** `/etc/nix/netrc`
2. `sudo chown root:root /etc/netrc`
3. `sudo chmod 600 /etc/netrc`
4. Added the following to my NixOS system config.
```
systemd.services.nix-daemon = {serviceConfig.Environment = "NETRC=/etc/netrc"; };
nix.settings.extra-sandbox-paths = ["etc/netrc"];
```
5. ran the build command as follows
```
nix build .#<package that needed the private python pacakge> --extra-sandbox-paths /etc/netrc
```

That's precisely what I have done to get it to build on one machine. I quickly tried on my other but something didn't work not sure what yet.. I also am curious what I can remove / simplify from the above and how to make this simple for non-NixOS machines. Can I add something to the flake to automatically do this?

**Comment by malteneuss** [comment]
I'm not sure how this would make a difference. The path to the file and access rights should be irrelevant to the nix daemon, which i think runs as root anyway (if you'r using nixos or have "multi-user install"). It would be great if you could try out different subsets of your steps.

I would doubt that a flake would allow you to modify random files on your machines.^^

**Comment by mcamp-ata** [comment]
yea the one difference between the two machines I tried this on was that the one that isn't working is configured to use LDAP for users. I generally have to for whatever reason restart the `nix-daemon` at boot. The system that everything worked is only local user. I did try on the LDAP machine running the `nix build` command as `root` and had no luck. I ran the command once right after a system reboot, before restarting the daemon and also after restarting the daemon with no luck. 

I will explore this some more and see what I can figure out.

**Comment by mcamp-ata** [comment]
I still haven't figured out whats different about a system that has LDAP user(s) VS one that is only local users. But I am able to build the package on other systems using `NETRC` as described above. 

I ran `nix run github:utdemir/nix-tree` on both systems and noticed that at the root of the tree of the LDAP system it has `home-manager-path` and on my non LDAP systems I have `user-environment`. So I wonder if there is some issue with `home-manager` and if maybe its being run as a different user or something and I need to make the `netrc` file owned by it.
