### ISSUE TITLE
opencv-python doesn't build, "ModuleNotFoundError: No module named 'skbuild'"

### ISSUE THREAD

**Issue by ShamrockLee** [nix-community/poetry2nix#155]
It doesn't happen before.
I'm not sure if it is related to the builder, or is an upstream issue.

* `nix-info -m`
  - system: `"x86_64-linux"`
  - host os: `Linux 4.19.136, NixOS, 20.09pre237279.8e2b14aceb1 (Nightingale)`
  - multi-user?: `yes`
  - sandbox: `yes`
  - version: `nix-env (Nix) 2.3.7`
  - channels(shamrock): `"home-manager"`
  - channels(root): `"nixos-20.09pre237279.8e2b14aceb1"`
  - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
* python version: 3.7.7
* `nix-build` output:
```console
[user@nixos:~/Projects/ShamrockLee/shadow-removal-numpy]$ nix-build ./poetry-env.nix 
these derivations will be built:
  /nix/store/0va3nqdbcmr75p1vbpr8af5qz1d9j4vc-python3.7-numpy-1.19.1.drv
  /nix/store/kw8bggvj2grzh786wlkwqqzyzrqpc7vs-opencv-python-4.4.0.42.tar.gz.drv
  /nix/store/wj8s4akp0j4afsji6hx3nz5r66xygf7a-python3.7-opencv-python-4.4.0.42.drv
  /nix/store/p0062icxk53206jaax99921kgbscm8ss-python3-3.7.8-env.drv
building '/nix/store/0va3nqdbcmr75p1vbpr8af5qz1d9j4vc-python3.7-numpy-1.19.1.drv'...
building '/nix/store/kw8bggvj2grzh786wlkwqqzyzrqpc7vs-opencv-python-4.4.0.42.tar.gz.drv'...
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/8mg14159j9jxjfldgzhdb9m5m5kwzkfd-numpy-1.19.1.zip
source root is numpy-1.19.1
setting SOURCE_DATE_EPOCH to timestamp 1595333652 of file numpy-1.19.1/PKG-INFO
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Removing pyproject.toml...
Creating a wheel...

trying https://files.pythonhosted.org/packages/source/o/opencv-python/opencv-python-4.4.0.42.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.                                                                                     
Processing /build/numpy-1.19.1
Building wheels for collected packages: numpy
  0     0    0     0    0     0      0      0 --:--:--  0:00:15 --:--:--     0
100 84.7M  100 84.7M    0     0  1712k      0  0:00:50  0:00:50 --:--:-- 2818k
  Building wheel for numpy (setup.py) ... done
  Created wheel for numpy: filename=numpy-1.19.1-cp37-cp37m-linux_x86_64.whl size=13671222 sha256=5519f197913ead5cd3a231f3b85fa0374795da67ac2540252b38483fbe3e20f1
  Stored in directory: /build/pip-ephem-wheel-cache-31unyggg/wheels/e2/03/ed/148233a45efc6285f2176d468844aacba40e5e0d57068dc076
Successfully built numpy
Finished creating a wheel...
Finished executing pipBuildPhase
installing
Executing pipInstallPhase
/build/numpy-1.19.1/dist /build/numpy-1.19.1
Processing ./numpy-1.19.1-cp37-cp37m-linux_x86_64.whl
Installing collected packages: numpy
  WARNING: The scripts f2py, f2py3 and f2py3.7 are installed in '/nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/bin' which is not on PATH.                  
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                                             
Successfully installed numpy-1.19.1
/build/numpy-1.19.1
Finished executing pipInstallPhase
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/core/_struct_ufunc_tests.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/core/_rational_tests.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/core/_umath_tests.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/core/_operand_flag_tests.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/core/_multiarray_tests.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/random/_generator.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/random/_philox.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/random/_sfc64.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/random/mtrand.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/random/_common.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/random/_pcg64.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/random/bit_generator.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/random/_mt19937.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/random/_bounded_integers.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/linalg/_umath_linalg.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/linalg/lapack_lite.cpython-37m-x86_64-linux-gnu.so
shrinking /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib/python3.7/site-packages/numpy/fft/_pocketfft_internal.cpython-37m-x86_64-linux-gnu.so
strip is /nix/store/a759kbr0kgccsxl6lfx0xv5i3c9x9bw9-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/lib  /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/bin
patching script interpreter paths in /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1
checking for references to /build/ in /nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1...
Rewriting #!/nix/store/5xqs6j12d49y15zkpizrhx58wnld7vq5-python3-3.7.8/bin/python3.7 to #!/nix/store/5xqs6j12d49y15zkpizrhx58wnld7vq5-python3-3.7.8
wrapping `/nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/bin/f2py'...
Rewriting #!/nix/store/5xqs6j12d49y15zkpizrhx58wnld7vq5-python3-3.7.8/bin/python3.7 to #!/nix/store/5xqs6j12d49y15zkpizrhx58wnld7vq5-python3-3.7.8
wrapping `/nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/bin/f2py3.7'...
Rewriting #!/nix/store/5xqs6j12d49y15zkpizrhx58wnld7vq5-python3-3.7.8/bin/python3.7 to #!/nix/store/5xqs6j12d49y15zkpizrhx58wnld7vq5-python3-3.7.8
wrapping `/nix/store/br8wkn1yb8pc3r0yjskwdqmf8c55jk0w-python3.7-numpy-1.19.1/bin/f2py3'...
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
pythonCatchConflictsPhase
pythonRemoveBinBytecodePhase
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
building '/nix/store/wj8s4akp0j4afsji6hx3nz5r66xygf7a-python3.7-opencv-python-4.4.0.42.drv'...
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/i0rbi692f7brfark06bhzxdi3ix8i1z6-opencv-python-4.4.0.42.tar.gz
source root is opencv-python-4.4.0.42
setting SOURCE_DATE_EPOCH to timestamp 1597607219 of file opencv-python-4.4.0.42/PKG-INFO
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Removing pyproject.toml...
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /build/opencv-python-4.4.0.42
    ERROR: Command errored out with exit status 1:
     command: /nix/store/5xqs6j12d49y15zkpizrhx58wnld7vq5-python3-3.7.8/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-_g3gdm0o/setup.py'"'"'; __file__='"'"'/build/pip-req-build-_g3gdm0o/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /build/pip-pip-egg-info-0849x740
         cwd: /build/pip-req-build-_g3gdm0o/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/build/pip-req-build-_g3gdm0o/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
builder for '/nix/store/wj8s4akp0j4afsji6hx3nz5r66xygf7a-python3.7-opencv-python-4.4.0.42.drv' failed with exit code 1
cannot build derivation '/nix/store/p0062icxk53206jaax99921kgbscm8ss-python3-3.7.8-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/p0062icxk53206jaax99921kgbscm8ss-python3-3.7.8-env.drv' failed

  ```

**Comment by NorfairKing** [comment]
This override yields a working `opencv-python` for me.

```
opencv-python = super.opencv-python.overridePythonAttrs (old: {
        nativeBuildInputs = [ pkgs.cmake ] ++ old.nativeBuildInputs;
        buildInputs = [ self.scikit-build ] ++ (old.buildInputs or []);
        dontUseCmakeConfigure = true;
      });
```

**Comment by kurnevsky** [comment]
It seems the same should be applied to `opencv-contrib-python`.

**Comment by adisbladis** [comment]
@kurnevsky a could you make a pr?

**Comment by kurnevsky** [comment]
https://github.com/nix-community/poetry2nix/pull/493
