### ISSUE TITLE
mongomock missing pbr override ?

### ISSUE THREAD

**Issue by teto** [nix-community/poetry2nix#164]
not sure that's the correct repository to post to: mongomock seems to miss a dependency ('pbr') and it doesn't seem present in nixpkgs either so my guess is that it is a missing override ?
```
Executing pythonImportsCheckPhase
wrapping `/nix/store/lnwxhqn70325r48qwr32m6dq5s5qcq8x-python3.8-flower-0.9.5/bin/flower'...
Executing pythonRemoveTestsDir
Finished executing pythonRemoveTestsDir
pythonCatchConflictsPhase
pythonRemoveBinBytecodePhase
pythonImportsCheckPhase
Executing pythonImportsCheckPhase
    ERROR: Command errored out with exit status 1:
     command: /nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-dzsug4pm/setup.py'"'"'; __file__='"'"'/build/pip-req-build-dzsug4pm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /build/pip-pip-egg-info-crpc_nd1
         cwd: /build/pip-req-build-dzsug4pm/
    Complete output (38 lines):
    WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff6b11550>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pbr/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5da4190>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pbr/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5da4310>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pbr/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5da4460>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pbr/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5da4580>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pbr/
    ERROR: Could not find a version that satisfies the requirement pbr (from versions: none)
    ERROR: No matching distribution found for pbr
    Traceback (most recent call last):
      File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp8_6o8ewc', '--quiet', 'pbr']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/build/pip-req-build-dzsug4pm/setup.py", line 4, in <module>
        setup(setup_requires=["pbr"], pbr=True)
      File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/__init__.py", line 160, in setup
        _install_setup_requires(attrs)
      File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/__init__.py", line 155, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/dist.py", line 695, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp8_6o8ewc', '--quiet', 'pbr']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
note: keeping build directory '/tmp/nix-build-python3.8-mongomock-3.20.0.drv-1'
error: --- Error --- nix-daemon
builder for '/nix/store/6qiqsrxv4g3b3ykl975f114zcd3234f0-python3.8-mongomock-3.20.0.drv' failed with exit code 1; last 10 log lines:
          return self.obtain(req, installer)
        File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1077, in obtain
          return installer(requirement)
        File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/dist.py", line 754, in fetch_build_egg
          return fetch_build_egg(self, req)
        File "/nix/store/rpgik653k5r1y9526nm2cgl6514rdjgx-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
          raise DistutilsError(str(e))
      distutils.errors.DistutilsError: Command '['/nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/bin/python3.8', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp8_6o8ewc', '--quiet', 'pbr']' returned non-zero exit status 1.
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
note: keeping build directory '/tmp/nix-build-python3.8-jsonnet-0.16.0.drv-1'
note: keeping build directory '/tmp/nix-build-python3.8-typed-ast-1.4.1.drv-1'
note: keeping build directory '/tmp/nix-build-python3.8-regex-2020.7.14.drv-1'
note: keeping build directory '/tmp/nix-build-python3.8-numpy-1.19.1.drv-1'
note: keeping build directory '/tmp/nix-build-python3.8-docutils-0.15.2.drv-1'
note: keeping build directory '/tmp/nix-build-python3.8-aiohttp-3.6.2.drv-1'
```
This seemed to work fine before I bumped my nixpkgs but that may coincide with a python package bump

**Comment by teto** [comment]
thanks
