### ISSUE TITLE
pystemmer fails to build due to "socket.gaierror: temporary failure in name resolution"

### ISSUE THREAD

**Issue by sotte** [nix-community/poetry2nix#1778]
### Describe the issue
pystemmer fails to build due to "socket.gaierror: temporary failure in name resolution". I have no idea what the reason could be or how to debug this.

I checked the wiki, the docs, and issues. Any pointers are highly appreciated.

### Additional context

```
❯ mkdir pystemmer_on_poetry2nix

❯ cd pystemmer_on_poetry2nix/

❯ nix flake init --template github:nix-community/poetry2nix
wrote: /home/stefan/tmp/pystemmer_on_poetry2nix/flake.nix
wrote: /home/stefan/tmp/pystemmer_on_poetry2nix/README.md
wrote: /home/stefan/tmp/pystemmer_on_poetry2nix/poetry.lock
wrote: /home/stefan/tmp/pystemmer_on_poetry2nix/app/__init__.py
wrote: /home/stefan/tmp/pystemmer_on_poetry2nix/app
wrote: /home/stefan/tmp/pystemmer_on_poetry2nix/pyproject.toml
 

❯ nix develop .#poetry
warning: creating lock file '/home/stefan/tmp/pystemmer_on_poetry2nix/flake.lock'

[stefan@arbeitstier:~/tmp/pystemmer_on_poetry2nix]$ poetry add --lock pystemmer
Creating virtualenv app-jaau7Ssp-py3.12 in /home/stefan/.cache/pypoetry/virtualenvs
Using version ^2.2.0.1 for pystemmer

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

[stefan@arbeitstier:~/tmp/pystemmer_on_poetry2nix]$
exit

❯ nix develop
error: builder for '/nix/store/xq8ifxqck4f8b6kbd5ivvivb84fpjrgz-python3.12-pystemmer-2.2.0.1.drv' failed with exit code 1;
       last 10 log lines:
       >   '"'"''"'"''"'"' % ('"'"'/build/PyStemmer-2.2.0.1/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /build/pip-pip-egg-info-4i827po5
       >   cwd: /build/PyStemmer-2.2.0.1/
       >   Preparing metadata (setup.py) ... error
       > error: metadata-generation-failed
       >
       > × Encountered error while generating package metadata.
       > ╰─> See above for output.
       >
       > note: This is an issue with the package mentioned above, not pip.
       > hint: See above for details.
       For full logs, run 'nix log /nix/store/xq8ifxqck4f8b6kbd5ivvivb84fpjrgz-python3.12-pystemmer-2.2.0.1.drv'.
error: 1 dependencies of derivation '/nix/store/kx0f0hczi66lm9z7kzp2xywa850xjg9l-nix-shell-env.drv' failed to build


❯ nix log /nix/store/xq8ifxqck4f8b6kbd5ivvivb84fpjrgz-python3.12-pystemmer-2.2.0.1.drv
...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Processing /build/PyStemmer-2.2.0.1
  Running command python setup.py egg_info
  Downloading https://snowballstem.org/dist/libstemmer_c-2.2.0.tar.gz... Traceback (most recent call last):
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/urllib/request.py", line 1344, in do_open
      h.request(req.get_method(), req.selector, req.data, headers,
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/http/client.py", line 1336, in request
      self._send_request(method, url, body, headers, encode_chunked)
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/http/client.py", line 1382, in _send_request
      self.endheaders(body, encode_chunked=encode_chunked)
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/http/client.py", line 1331, in endheaders
      self._send_output(message_body, encode_chunked=encode_chunked)
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/http/client.py", line 1091, in _send_output
      self.send(msg)
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/http/client.py", line 1035, in send
      self.connect()
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/http/client.py", line 1470, in connect
      super().connect()
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/http/client.py", line 1001, in connect
      self.sock = self._create_connection(
                  ^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/socket.py", line 829, in create_connection
      for res in getaddrinfo(host, port, 0, SOCK_STREAM):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/socket.py", line 964, in getaddrinfo
      for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  socket.gaierror: [Errno -3] Temporary failure in name resolution

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/build/PyStemmer-2.2.0.1/setup.py", line 126, in <module>
      LIBRARY_SOURCE_CODE.download()
    File "/build/PyStemmer-2.2.0.1/setup.py", line 110, in download
      download_and_extract_tarball(
    File "/build/PyStemmer-2.2.0.1/tarballfetcher.py", line 40, in download_and_extract_tarball
      download_file(tarball_url, tarball_filename)
    File "/build/PyStemmer-2.2.0.1/tarballfetcher.py", line 17, in download_file
      urlretrieve(url, filename)
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/urllib/request.py", line 240, in urlretrieve
      with contextlib.closing(urlopen(url, data)) as fp:
                              ^^^^^^^^^^^^^^^^^^
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/urllib/request.py", line 215, in urlopen
      return opener.open(url, data, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/urllib/request.py", line 515, in open
      response = self._open(req, data)
                 ^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/urllib/request.py", line 532, in _open
      result = self._call_chain(self.handle_open, protocol, protocol +
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/urllib/request.py", line 492, in _call_chain
      result = func(*args)
               ^^^^^^^^^^^
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/urllib/request.py", line 1392, in https_open
      return self.do_open(http.client.HTTPSConnection, req,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nix/store/04gg5w1s662l329a8kh9xcwyp0k64v5a-python3-3.12.4/lib/python3.12/urllib/request.py", line 1347, in do_open
      raise URLError(err)
  urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
  error: subprocess-exited-with-error
```
 

`flake.nix` from `nix flake init --template github:nix-community/poetry2nix`:
```nix
{
  description = "Application packaged using poetry2nix";

  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable-small";
    poetry2nix = {
      url = "github:nix-community/poetry2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, poetry2nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        # see https://github.com/nix-community/poetry2nix/tree/master#api for more functions and examples.
        pkgs = nixpkgs.legacyPackages.${system};
        inherit (poetry2nix.lib.mkPoetry2Nix { inherit pkgs; }) mkPoetryApplication;
      in
      {
        packages = {
          myapp = mkPoetryApplication { projectDir = self; };
          default = self.packages.${system}.myapp;
        };

        # Shell for app dependencies.
        #
        #     nix develop
        #
        # Use this shell for developing your app.
        devShells.default = pkgs.mkShell {
          inputsFrom = [ self.packages.${system}.myapp ];
        };

        # Shell for poetry.
        #
        #     nix develop .#poetry
        #
        # Use this shell for changes to pyproject.toml and poetry.lock.
        devShells.poetry = pkgs.mkShell {
          packages = [ pkgs.poetry ];
        };
      });
}

```

`pyproject.toml`:
```toml
[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pystemmer = "^2.2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

`poetry.lock`:
```toml
# This file is automatically @generated by Poetry 1.8.3 and should not be changed by hand.

[[package]]
name = "pystemmer"
version = "2.2.0.1"
description = "Snowball stemming algorithms, for information retrieval"
optional = false
python-versions = "*"
files = [
    {file = "PyStemmer-2.2.0.1.tar.gz", hash = "sha256:9f3b366f1ed06b49dc1868bf0aefd884423db80f3431be442d0f993e448cc67b"},
]

[metadata]
lock-version = "2.0"
python-versions = "^3.11"
content-hash = "86c07e697a168917ad3d89ff68c444980535a4c3cf6c75f61d9c8999d3712c11"
```

**Comment by adisbladis** [comment]
This is pystemmer trying to download native libraries at build time: https://github.com/snowballstem/pystemmer/blob/master/setup.py#L35.
You should be able to fix this with an override that adds `libstemmer`:
https://github.com/snowballstem/pystemmer/blob/master/setup.py#L117-L118
