### ISSUE TITLE
Unable to install `seolib` library

### ISSUE THREAD

**Issue by suryasr007** [nix-community/poetry2nix#203]
Getting following error while installing `seolib` library. Seems like there isn't ay Nix package associated with `seolib`. 

```bash
.
.
.
  /nix/store/wwkmgxig2h33kgkd526v72a1hdks95kh-python3.7-repoze-workflow-1.0b1.drv
  /nix/store/qlpb44w3arkv63fndfa9y3nnd64yg81c-python3-3.7.6-env.drv
building '/nix/store/7a4pbi92b28idygil573bnmylzwk54y1-seolib-0.1.3.win32.exe.drv'...

trying https://files.pythonhosted.org/packages/source/s/seolib/seolib-0.1.3.win32.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
error: cannot download seolib-0.1.3.win32.exe from any mirror
builder for '/nix/store/7a4pbi92b28idygil573bnmylzwk54y1-seolib-0.1.3.win32.exe.drv' failed with exit code 1
cannot build derivation '/nix/store/ivm2bq1yh1sinx108lxrqrrwgi1ym182-python3.7-seolib-0.1.3.drv': 1 dependencies couldn't be built
building '/nix/store/0jr8slqsgnbwpfzpkp28kkyifbnzqimz-slugify-0.0.1.tar.gz.drv'...
cannot build derivation '/nix/store/qlpb44w3arkv63fndfa9y3nnd64yg81c-python3-3.7.6-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/qlpb44w3arkv63fndfa9y3nnd64yg81c-python3-3.7.6-env.drv' failed
```

**poetry.lock:**
```toml
[[package]]
category = "main"
description = "Python lib that provides you with some usefull and simple methods to obtain website metrics"
name = "seolib"
optional = false
python-versions = "*"
version = "0.1.3"


seolib = [
    {file = "seolib-0.1.3.win32.exe", hash = "sha256:72d26aaf3196592a301dd29bd09f3aedd816836cd0de1ab927734f996156fee1"},
    {file = "seolib-0.1.3.zip", hash = "sha256:a6d2ca992a07e3b1defc88bcc4bdc5cca9e616d02b022346e133d0f8050a824b"},
]
```

**pyproject.toml:**
```toml
seolib = "==0.1.3"
```

**Specs:**
OS: MacOS Catalina
Nix branch: 20.03

**Comment by Infinisil** [comment]
It works on Linux at least, but it looks like seolib is broken at runtime too for Python 3:
```
>>> import seolib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/f469gdb7cmdv5zc4kpm1hrmf82rgpdhh-python3-3.7.6-env/lib/python3.7/site-packages/seolib/__init__.py", line 6, in <module>
    from api import get_seomoz_data
ModuleNotFoundError: No module named 'api'
```

Looks like that package is severely outdated and unmaintained, see https://stackoverflow.com/questions/56677796/how-to-fix-cannot-import-name-get-seomoz-data-from-api-error-in-python

So I think the best solution here is to not even attempt to use that package

**Comment by suryasr007** [comment]
Thanks! Closing this issue as the package is broken at runtime for Python 3.
