### ISSUE TITLE
cvxpy build fails with RuntimeError: CMake must be installed to build OSQP

### ISSUE THREAD

**Issue by ilikeavocadoes** [nix-community/poetry2nix#206]
If I run first `poetry add cmake` and then `poetry add cvxpy` and then try to build, the build of cmake fails with the same error as in https://github.com/nix-community/poetry2nix/issues/155.

nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.73, NixOS, 20.09.1599.d105075a1fd (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.7`
 - channels(root): `"nixos-20.09.1599.d105075a1fd, nixos-previous-18.09.2574.a7e559a5504, nixos-unstable-21.03pre250162.34ad166a830"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

python version: 3.8.5
nix-build output:
```
these derivations will be built:
  /nix/store/6q9xqj7yr0wxnnhd6flwadhl6491r25k-python3.8-osqp-0.6.1.drv
  /nix/store/8zn362856wz8wayfg7q62vk5jn1a87sq-python3.8-ecos-2.0.7.post1.drv
  /nix/store/ywpc5yhs13dks9663fq2j2dlcklacplq-python3.8-scs-2.1.2.drv
  /nix/store/q8mp4r81i04fx51qvbpmmm9qpbz5qk7c-python3.8-cvxpy-1.1.7.drv
  /nix/store/6hb3fjqhj1d348a174l52hg16bi6gnvl-python3-3.8.5-env.drv
building '/nix/store/8zn362856wz8wayfg7q62vk5jn1a87sq-python3.8-ecos-2.0.7.post1.drv'...
building '/nix/store/6q9xqj7yr0wxnnhd6flwadhl6491r25k-python3.8-osqp-0.6.1.drv'...
building '/nix/store/ywpc5yhs13dks9663fq2j2dlcklacplq-python3.8-scs-2.1.2.drv'...
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing python-recompile-bytecode-hook.sh
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/94lg6pq5r8ac4ccv7aqqmq78axq0z9bp-ecos-2.0.7.post1.tar.gz
source root is ecos-2.0.7.post1
unpacking sources
unpacking source archive /nix/store/2ajdah38pmcn6izyynxsn987zp6gf44z-osqp-0.6.1.tar.gz
setting SOURCE_DATE_EPOCH to timestamp 1542443129 of file ecos-2.0.7.post1/src/ecos/version.py
patching sources
unpacking sources
unpacking source archive /nix/store/1z39jl93jc60pcnv3g5g7mm9iy9rzfvl-scs-2.1.2.tar.gz
configuring
source root is osqp-0.6.1
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
setting SOURCE_DATE_EPOCH to timestamp 1567278497 of file osqp-0.6.1/setup.cfg
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
source root is scs-2.1.2
setting SOURCE_DATE_EPOCH to timestamp 1585161473 of file scs-2.1.2/setup.cfg
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /build/ecos-2.0.7.post1
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /build/osqp-0.6.1
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /build/scs-2.1.2
Building wheels for collected packages: ecos
Building wheels for collected packages: osqp
  Building wheel for osqp (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-otn30ti1/setup.py'"'"'; __file__='"'"'/build/pip-req-build-otn30ti1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /build/pip-wheel-7frg5q2m
       cwd: /build/pip-req-build-otn30ti1/
  Complete output (122 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/osqp
  copying module/utils.py -> build/lib.linux-x86_64-3.8/osqp
  copying module/__init__.py -> build/lib.linux-x86_64-3.8/osqp
  copying module/interface.py -> build/lib.linux-x86_64-3.8/osqp
  creating build/lib.linux-x86_64-3.8/osqp/codegen
  copying module/codegen/utils.py -> build/lib.linux-x86_64-3.8/osqp/codegen
  copying module/codegen/__init__.py -> build/lib.linux-x86_64-3.8/osqp/codegen
  copying module/codegen/code_generator.py -> build/lib.linux-x86_64-3.8/osqp/codegen
  creating build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/feasibility_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/dual_infeasibility_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/unconstrained_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/warm_start_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/update_matrices_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/basic_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/non_convex_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/codegen_vectors_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/mkl_pardiso_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/__init__.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/codegen_matrices_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/primal_infeasibility_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  copying module/tests/polishing_test.py -> build/lib.linux-x86_64-3.8/osqp/tests
  creating build/lib.linux-x86_64-3.8/osqppurepy
  copying modulepurepy/_osqp.py -> build/lib.linux-x86_64-3.8/osqppurepy
  copying modulepurepy/__init__.py -> build/lib.linux-x86_64-3.8/osqppurepy
  copying modulepurepy/interface.py -> build/lib.linux-x86_64-3.8/osqppurepy
  running egg_info
  writing osqp.egg-info/PKG-INFO
  writing dependency_links to osqp.egg-info/dependency_links.txt
  writing requirements to osqp.egg-info/requires.txt
  writing top-level names to osqp.egg-info/top_level.txt
  reading manifest file 'osqp.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'osqp.egg-info/SOURCES.txt'
  creating build/lib.linux-x86_64-3.8/osqp/codegen/files_to_generate
  copying module/codegen/files_to_generate/CMakeLists.txt -> build/lib.linux-x86_64-3.8/osqp/codegen/files_to_generate
  copying module/codegen/files_to_generate/emosqpmodule.c -> build/lib.linux-x86_64-3.8/osqp/codegen/files_to_generate
  copying module/codegen/files_to_generate/example.c -> build/lib.linux-x86_64-3.8/osqp/codegen/files_to_generate
  copying module/codegen/files_to_generate/setup.py -> build/lib.linux-x86_64-3.8/osqp/codegen/files_to_generate
  creating build/lib.linux-x86_64-3.8/osqp/codegen/sources
  creating build/lib.linux-x86_64-3.8/osqp/codegen/sources/configure
  copying module/codegen/sources/configure/osqp_configure.h.in -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/configure
  copying module/codegen/sources/configure/qdldl_types.h.in -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/configure
  creating build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/CMakeLists.txt -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/auxil.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/constants.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/error.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/glob_opts.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/kkt.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/lin_alg.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/osqp.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/proj.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/qdldl.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/qdldl_interface.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/scaling.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/types.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  copying module/codegen/sources/include/util.h -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/include
  creating build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/CMakeLists.txt -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/auxil.c -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/error.c -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/kkt.c -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/lin_alg.c -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/osqp.c -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/proj.c -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/qdldl.c -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/qdldl_interface.c -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/scaling.c -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  copying module/codegen/sources/src/util.c -> build/lib.linux-x86_64-3.8/osqp/codegen/sources/src
  running build_ext
  Traceback (most recent call last):
    File "/build/pip-req-build-otn30ti1/setup.py", line 164, in build_extensions
      check_output(['cmake', '--version'])
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/subprocess.py", line 1702, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'cmake'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/build/pip-req-build-otn30ti1/setup.py", line 208, in <module>
      setup(name='osqp',
    File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/nix/store/pc0rjkhv9lrcns6dld4nx75m8hqsqfkm-python3.8-python3.8-wheel-0.34.2/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/nix/store/vliz92p6b5ykk3xqyd8rr6kiv50flfnd-python3.8-setuptools-47.3.1/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 87, in run
      _build_ext.run(self)
    File "/nix/store/z65l1jqvxa58zzwwa3bvglb6asj4y8cv-python3-3.8.5/lib/python3.8/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/build/pip-req-build-otn30ti1/setup.py", line 166, in build_extensions
      raise RuntimeError("CMake must be installed to build OSQP")
  RuntimeError: CMake must be installed to build OSQP
  ----------------------------------------
  ERROR: Failed building wheel for osqp
  Running setup.py clean for osqp
Building wheels for collected packages: scs
Failed to build osqp
ERROR: Failed to build one or more wheels
builder for '/nix/store/6q9xqj7yr0wxnnhd6flwadhl6491r25k-python3.8-osqp-0.6.1.drv' failed with exit code 1
cannot build derivation '/nix/store/6hb3fjqhj1d348a174l52hg16bi6gnvl-python3-3.8.5-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/6hb3fjqhj1d348a174l52hg16bi6gnvl-python3-3.8.5-env.drv' failed
```

**Comment by adisbladis** [comment]
I think you'll need to add `cmake` (NOT the Python package cmake, but the native one) to `nativeBuildInputs`.

**Comment by ilikeavocadoes** [comment]
> I think you'll need to add `cmake` (NOT the Python package cmake, but the native one) to `nativeBuildInputs`.

That seems to be it. Thanks for the help!
