### ISSUE TITLE
`packaging` 4.17.1 fails after setup.py has been removed

### ISSUE THREAD

**Issue by andir** [nix-community/poetry2nix#218]
On a project that I am working on I ran `poetry update --lock` today and it bumped some dependencies and most notably `packaging` from version 20.4 to 20.7 (https://github.com/pypa/packaging/compare/20.4...20.7). In that version range they removed the setup.py and moved to `pyproject.toml` and apparently are using `flit_core` for packaging `packaging`.

I created a minimal reproducer here: https://github.com/andir/poetry2nix-packaging-bug

```console
$ nix-shell
these derivations will be built:
  /nix/store/b4gq09aswb02nyy92jsrjdi7pwz59scr-python3.8-packaging-20.7.drv
  /nix/store/f5v5lldfxybxq9lddifd57xzcjs6dn9h-python3-3.8.6-env.drv
building '/nix/store/b4gq09aswb02nyy92jsrjdi7pwz59scr-python3.8-packaging-20.7.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/jiy6yqdab9ff1221mvsj8ay4ach9nn6g-packaging-20.7.tar.gz
source root is packaging-20.7
setting SOURCE_DATE_EPOCH to timestamp 1606573367 of file packaging-20.7/packaging/__init__.py
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /build/packaging-20.7
    Preparing wheel metadata ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/commands/wheel.py", line 155, in run
    requirement_set = resolver.resolve(
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 540, in _generate_metadata
    return generate_metadata(
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_internal/operations/build/metadata.py", line 33, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 176, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/nix/store/2klvsbgj53mykg8v3prsi65yj3v55szh-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/nix/store/5aq2ix4vmk8bxs20ddqi48vc4bnk8zr5-python3-3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flit_core'


builder for '/nix/store/b4gq09aswb02nyy92jsrjdi7pwz59scr-python3.8-packaging-20.7.drv' failed with exit code 2
```

Simply adding an override that add `flit-core` to `buildInputs` of `packaging` did solve the issue but feels kinda wrong and very impure as that version is now dependant on whatever version of that package we have in nixpkgs. 

My question: Should poetry not track this or is this a limitation of our tooling here?

**Comment by andir** [comment]
I updated my projects dependencies today and could remove my custom override as apparently a newer version has fixed the issue.

**Comment by lovesegfault** [comment]
This is happening again since `typing-extensions`got rid of their setup.py

**Comment by dz0ny** [comment]
for those that come from Google, full fix for black:
```nix
  poetryOverrides = self: super: {

    tomli = super.tomli.overridePythonAttrs (
      old: {
        buildInputs = (old.buildInputs or [ ]) ++ [ self.flit-core ];
      }
    );

    typing-extensions = super.typing-extensions.overridePythonAttrs (
      old: {
        buildInputs = (old.buildInputs or [ ]) ++ [ self.flit-core ];
      }
    );

    platformdirs = super.platformdirs.overridePythonAttrs (
      old: {
        postPatch = ''
          substituteInPlace setup.py --replace 'setup()' 'setup(version="${old.version}")'
        '';
      }
    );

    black = super.black.overridePythonAttrs (
      old: {
        buildInputs = (old.buildInputs or [ ]) ++ [ self.flit-core self.platformdirs ];
      }
    );

  };
```

You need to do the above for every package in the chain so it's a bit tiresome.

**Comment by side2k** [comment]
Since this issue is still out there, this could help people coming from Google:
```nix
pkgs.poetry2nix.mkPoetryApplication {
  projectDir = ./.;

  overrides = pkgs.poetry2nix.overrides.withDefaults (self: super: {

    pathspec = super.pathspec.overridePythonAttrs (
      old: {
        buildInputs = (old.buildInputs or [ ]) ++ [ self.flit-core ];
      }
    );
  });
}
```

**Comment by ChronosMOT** [comment]
Just in time
Thank you
