### ISSUE TITLE
Getting numpy to build when torch is a depndency.

### ISSUE THREAD

**Issue by NorfairKing** [nix-community/poetry2nix#230]
I have a project where `numpy` works when I add it using poetry, but when I then add `poetry add torch`, I get the following error:

```
unpacking sources
tail: error writing 'standard output': Broken pipe
Creating directory NVIDIA-Linux-x86_64-455.45.01
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/2h4zpacjqwwn4jp8i6mz1z8ipvr9yysf-numpy-1.18.1.zip

trying https://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_linux.run
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
source root is numpy-1.18.1
setting SOURCE_DATE_EPOCH to timestamp 1578308110 of file numpy-1.18.1/PKG-INFO
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Removing pyproject.toml...
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /build/numpy-1.18.1
unpacking sources
Building wheels for collected packages: numpy
Creating directory pkg
  Building wheel for numpy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /nix/store/papbnjfxwrdkmz6xfp7v2q7nxyvgcr5l-python3-3.8.6/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-uv9ukbgw/setup.py'"'"'; __file__='"'"'/build/pip-req-build-uv9ukbgw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /build/pip-wheel-iz6zlk14
       cwd: /build/pip-req-build-uv9ukbgw/
  Complete output (32 lines):
  Running from numpy source directory.
  Cythonizing sources
  Processing numpy/random/_bounded_integers.pxd.in
  Processing numpy/random/_generator.pyx
  Traceback (most recent call last):
    File "/build/pip-req-build-uv9ukbgw/tools/cythonize.py", line 61, in process_pyx
      from Cython.Compiler.Version import version as cython_version
  ModuleNotFoundError: No module named 'Cython'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/build/pip-req-build-uv9ukbgw/tools/cythonize.py", line 238, in <module>
      main()
    File "/build/pip-req-build-uv9ukbgw/tools/cythonize.py", line 234, in main
      find_process_files(root_dir)
    File "/build/pip-req-build-uv9ukbgw/tools/cythonize.py", line 225, in find_process_files
      process(root_dir, fromfile, tofile, function, hash_db)
    File "/build/pip-req-build-uv9ukbgw/tools/cythonize.py", line 191, in process
      processor_function(fromfile, tofile)
    File "/build/pip-req-build-uv9ukbgw/tools/cythonize.py", line 66, in process_pyx
      raise OSError('Cython needs to be installed in Python as a module')
  OSError: Cython needs to be installed in Python as a module
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/build/pip-req-build-uv9ukbgw/setup.py", line 488, in <module>
      setup_package()
    File "/build/pip-req-build-uv9ukbgw/setup.py", line 469, in setup_package
      generate_cython()
    File "/build/pip-req-build-uv9ukbgw/setup.py", line 275, in generate_cython
      raise RuntimeError("Running cythonize failed!")
  RuntimeError: Running cythonize failed!
  ----------------------------------------
  ERROR: Failed building wheel for numpy
  Running setup.py clean for numpy
  ERROR: Command errored out with exit status 1:
   command: /nix/store/papbnjfxwrdkmz6xfp7v2q7nxyvgcr5l-python3-3.8.6/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-uv9ukbgw/setup.py'"'"'; __file__='"'"'/build/pip-req-build-uv9ukbgw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /build/pip-req-build-uv9ukbgw
  Complete output (10 lines):
  Running from numpy source directory.

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).

  ----------------------------------------
  ERROR: Failed cleaning build dir for numpy
Failed to build numpy

```

This perplexes me because I see that there is a poetry override for both numpy and torch and it includes `cython`. Any idea what this might be?

**Comment by NorfairKing** [comment]
CC @timokau because you made the torch overlay.

**Comment by NorfairKing** [comment]
@timokau It looks like you used `super` instead of `self` in your torch override.
This override yields a working torch for me:

```
      torch = super.torch.overrideAttrs (old:
        { 
          enableCuda = true;

          # This needs to be added because of a bug in poetry2nix where they use super instead of self, I think
          # TODO open an issue about this when I can confirm this.
          buildInputs = old.buildInputs ++ [ super.typing-extensions ];
          propagatedBuildInputs = [
            self.numpy 
            self.future
          ];          
        }    
```

**Comment by timokau** [comment]
Thanks for investigating @NorfairKing! You're right, I should have used `self` for the dependencies (`buildInputs` too). Can you open a PR for this?

**Comment by NorfairKing** [comment]
@timokau Will do!
