### ISSUE TITLE
Cannot reference package using {path = "../<package>", develop = true}

### ISSUE THREAD

**Issue by confususs** [nix-community/poetry2nix#284]
First I want to say thank you for all the hard work on this project! I really love it & I'm trying to transfer all my poetry projects to it. :smile: 

Currently I'm using poetry within a nix-shell, where I have the following layout:

```
├── consumer
│   ├── consumer
│   │   └── main.py
│   └── pyproject.toml
├── core
│   ├── core
│   │   └── models.py
│   └── pyproject.toml
├── poetry.lock
├── pyproject.toml
└── shell.nix
```

You can check it out @ https://github.com/confususs/poetry2nix-example. 

The idea is to be able to have 1 'core package' which can be consumed by multiple packages. Each package has its own `pyproject.toml` & `poetry.lock`. 

On top of that, I've defined another `pyproject.toml` & `poetry.lock` on the top level of the repository so that I can easily access all my installed packages within my IDE once I called `poetry install` after calling `nix-shell`. This seems to work fine. (to reproduce this, uncomment `myAppEnv` in the shell.nix)

However, I'd like to use poetry2nix to automatically install all my dependencies for me once I enter my nix-shell, but the configuration is deemed incorrect somehow. See the output:

```
poetry2nix-example on  main is 📦 v0.1.0 via 🐍 v3.8.8 (python-3.8.8)took 4s
➜ nix-shell
these derivations will be built:
  /nix/store/mkw9lzys7xypd4xnqcr22dl23pr2m7b9-python3.8-consumer-0.1.0.drv
  /nix/store/2b6irdl3w72nbjvr7a383fy4mj2rv96s-python3-3.8.8-env.drv
building '/nix/store/mkw9lzys7xypd4xnqcr22dl23pr2m7b9-python3.8-consumer-0.1.0.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/g7r0v3d6s3mircyisc67bsq3pgjllqyw-source
source root is source
setting SOURCE_DATE_EPOCH to timestamp 315619200 of file source/pyproject.toml
patching sources
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /build/source
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /nix/store/d44wd6n98f93hjr6q1d1phhh1hw7a17d-python3-3.8.8/bin/python3.8 /nix/store/3vxcwng146imgrmdhzk86g1f8bhlp6a4-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /build/tmpbl3k3ld5
         cwd: /build/pip-req-build-ppiq552z
    Complete output (14 lines):
    Traceback (most recent call last):
      File "/nix/store/3vxcwng146imgrmdhzk86g1f8bhlp6a4-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/nix/store/3vxcwng146imgrmdhzk86g1f8bhlp6a4-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/nix/store/3vxcwng146imgrmdhzk86g1f8bhlp6a4-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/nix/store/752fzqnrm03y96fwbp96vj6h4wshhqv2-python3.8-poetry-core-1.0.2/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
        poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
      File "/nix/store/752fzqnrm03y96fwbp96vj6h4wshhqv2-python3.8-poetry-core-1.0.2/lib/python3.8/site-packages/poetry/core/factory.py", line 43, in create_poetry
        raise RuntimeError("The Poetry configuration is invalid:\n" + message)
    RuntimeError: The Poetry configuration is invalid:
      - [dependencies.core] {'develop': True, 'version': '*'} is not valid under any of the given schemas

    ----------------------------------------
ERROR: Command errored out with exit status 1: /nix/store/d44wd6n98f93hjr6q1d1phhh1hw7a17d-python3-3.8.8/bin/python3.8 /nix/store/3vxcwng146imgrmdhzk86g1f8bhlp6a4-python3.8-pip-20.2.4/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /build/tmpbl3k3ld5 Check the logs for full command output.

builder for '/nix/store/mkw9lzys7xypd4xnqcr22dl23pr2m7b9-python3.8-consumer-0.1.0.drv' failed with exit code 1
cannot build derivation '/nix/store/2b6irdl3w72nbjvr7a383fy4mj2rv96s-python3-3.8.8-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/2b6irdl3w72nbjvr7a383fy4mj2rv96s-python3-3.8.8-env.drv' failed
```

I can't seem to figure out why the configuration is seen as invalid through poetry2nix, while it seems to be valid when I use poetry within my shell. 

Any ideas or pointers? :)

**Comment by kiril-me** [comment]
I have the same issue. Any suggestions to workaround it?
