### ISSUE TITLE
ignore packages required for alien platforms (e.g., windows)

### ISSUE THREAD

**Issue by teto** [nix-community/poetry2nix#287]
while trying to run poetry2nix for one of my project, I get an error because `nix develop` tries to build cmd2 which triggers a build  of pyreadline  (which fails) except cmd2 requires pyreadline only on windows https://github.com/python-cmd2/cmd2/blob/33a451db7b911a5a5ee5a3473a2e07eeeb308e55/setup.py#L56 :

```
error: builder for '/nix/store/6brbx4ih6m7f10si65ss4c5nv5rc2h0m-python3.8-pyreadline3-3.3.drv' failed with exit code 1;
       last 10 log lines:
       >      command: /nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-trji6aq6/setup.py'"'"'; __file__='"'"'/build/pip-req-build-trji6aq6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /build/pip-pip-egg-info-sgoju1ad
       >          cwd: /build/pip-req-build-trji6aq6/
       >     Complete output (5 lines):
       >     Traceback (most recent call last):
       >       File "<string>", line 1, in <module>
       >       File "/build/pip-req-build-trji6aq6/setup.py", line 21, in <module>
       >         raise RuntimeError('pyreadline3 is for Windows only, not {}.'.format(_S))
       >     RuntimeError: pyreadline3 is for Windows only, not Linux.
       >     ----------------------------------------
       > ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
       For full logs, run 'nix log /nix/store/6brbx4ih6m7f10si65ss4c5nv5rc2h0m-python3.8-pyreadline3-3.3.drv'.
error: 1 dependencies of derivation '/nix/store/qrghk888y5sv378j7d9hdx75j6h7xlpf-python3.8-cmd2-1.5.0.drv' failed to build
```

Can't poetry2nix ignore it since I am not on windows ? I removed the dependency from poetry.lock as a workaround.

**Comment by adisbladis** [comment]
Could you upload the relevant `pyproject.toml`/`poetry.lock` files so I can reproduce the issue?

**Comment by teto** [comment]
problem is gone during another fix. Will reopen with a way to reproduce it that happens again. Sorry for the noise.
