### ISSUE TITLE
How to depend on torch with newer cudatoolkit?

### ISSUE THREAD

**Issue by NorfairKing** [nix-community/poetry2nix#301]
I'm trying to use torch with cudatoolkit 11.1 (We cannot depend on 10.2 because of newer hardware, I think).

```
$ python
Python 3.8.5 (default, Jul 20 2020, 13:26:22) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.Tensor([1,2,3]).cuda()
/nix/store/k9ar7x52n7pg0mk0whmb5bsigapwk8gs-python3-3.8.5-env/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning: 
Graphics Device with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the Graphics Device GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: unknown error
>>> niv update
  File "<stdin>", line 1
    niv update
        ^
SyntaxError: invalid syntax
```

I've tried many things, the latest of which is to use the packages at these urls:
```
https://download.pytorch.org/whl/cu111/torch-1.8.1%2Bcu111-cp39-cp39-linux_x86_64.whl
https://download.pytorch.org/whl/cu111/torchvision-0.9.1%2Bcu111-cp39-cp39-linux_x86_64.whl
```
(from https://download.pytorch.org/whl/torch_stable.html)

I keep running into trouble. 

When I put this in my `pyproject.toml`, poetry doesn't even succesfully lock:
```
torch = { url = "https://download.pytorch.org/whl/cu111/torch-1.8.1%2Bcu111-cp39-cp39-linux_x86_64.whl" }
torchvision = { url = "https://download.pytorch.org/whl/cu111/torchvision-0.9.1%2Bcu111-cp39-cp39-linux_x86_64.whl" }
```
It says:
```
$ poetry lock
Updating dependencies
Resolving dependencies... (61.8s)

  SolverProblemError

  Because torchvision (0.9.1+cu111 url) depends on torch (1.8.1)
   and relu-monorepo depends on torch (1.8.1+cu111 url), torchvision is forbidden.
  So, because relu-monorepo depends on torchvision (0.9.1+cu111 url), version solving failed.

  at /nix/store/14arb7420p82ygzyplgg83mr15pcmf8z-python3.8-poetry-1.1.4/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

This looks like a limitation of poetry, so I'm not sure what to do about it ..

When instead I put only this in my `pyproject.toml`, poetry succesfully locks: 

```
torch = { url = "https://download.pytorch.org/whl/cu111/torch-1.8.1%2Bcu111-cp39-cp39-linux_x86_64.whl" }
```

But then when I try to start my nix-shell, I get this cryptic error:

```
$  nix-shell

warning: dumping very large path (> 256 MiB); this may run out of memory
unpacking 'https://download.pytorch.org/whl/cu111/torch-1.8.1%2Bcu111-cp39-cp39-linux_x86_64.whl'...
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
error: program 'tar' failed with exit code 2
(use '--show-trace' to show detailed location information)
```
It makes sense that tar would say that this doesn't like a tar archive, because it isn't one, but it's surprising to me that poetry2nix would try to use tar on this not-an-archive thing. 

Any advice would be appreciated. @adisbladis

**Comment by NorfairKing** [comment]
This hasn't been fixed, but I ended up using `nixpkgs.python38Packages.pytorch-bin` in an override.
