### ISSUE TITLE
Cannot build package with PyQt5 dependency

### ISSUE THREAD

**Issue by vlaci** [nix-community/poetry2nix#32]
Repro:
```
poetry2nix $ git rev-parse HEAD
0d5719df26ccc614684f8a5500fedead29612782
poetry2nix$ patch -p1 <<EOF                                                                                                                                                          🐍 .venv ..it/github.com/nix-community/poetry2nix 
diff --git a/tests/trivial/pyproject.toml b/tests/trivial/pyproject.toml
index 7625d49..5ce56f8 100644
--- a/tests/trivial/pyproject.toml
+++ b/tests/trivial/pyproject.toml
@@ -6,8 +6,7 @@ authors = ["Your Name <you@example.com>"]

 [tool.poetry.dependencies]
 python = "^3.6"
-alembic = "1.0.10"
-Flask = "^1.1.1"
+PyQt5 = "^5.14"

 [build-system]
 requires = ["poetry>=0.12"]
EOF
patching file tests/trivial/pyproject.toml
poetry2nix $ (cd tests/trivial && poetry lock)
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file
poetry2nix $ nix-build -A trivial tests
these derivations will be built:
  /nix/store/6fq5vhfwsmpqwq639lxkzh7xnlcqzar4-python3.7-pyqt5-5.14.1.drv
  /nix/store/03z2bxdqmkxr5m8b3fgfvv89v0nhqnk1-trivial-0.1.0.drv
building '/nix/store/6fq5vhfwsmpqwq639lxkzh7xnlcqzar4-python3.7-pyqt5-5.14.1.drv'...
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
unpacking sources
unpacking source archive /nix/store/ifjnd4kyqyynxfhvfn7ba2jhb4d28izi-PyQt5-5.14.1.tar.gz
source root is PyQt5-5.14.1
setting SOURCE_DATE_EPOCH to timestamp 1578245873 of file PyQt5-5.14.1/PKG-INFO
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "/nix/store/k5rdcbcwwpvj7l9f1yvd5mfggcfz16kk-python3-3.7.5/lib/python3.7/tokenize.py", line 447, in open
    buffer = _builtin_open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'setup.py'
builder for '/nix/store/6fq5vhfwsmpqwq639lxkzh7xnlcqzar4-python3.7-pyqt5-5.14.1.drv' failed with exit code 1
cannot build derivation '/nix/store/03z2bxdqmkxr5m8b3fgfvv89v0nhqnk1-trivial-0.1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/03z2bxdqmkxr5m8b3fgfvv89v0nhqnk1-trivial-0.1.0.drv' failed
poetry2nix $ echo $?
100
```

**Comment by adisbladis** [comment]
The overrides required to build pyqt5 added in 8591164784c9ce09d2edc1356068c03674199038, mostly through.

It also requires you to add `sip` to your environment as the one in nixpkgs is too old to build the latest pyqt.

**Comment by adisbladis** [comment]
@vlaci I just added feature parity with the nixpkgs derivation. You can now also do the following using poetry2nix:

``` nix
poetry2nix.mkPoetryApplication {
  overrides = [
    poetry2nix.defaultPoetryOverrides
    (self: super: {
      pyqt5 = super.pyqt5.override { withConnectivity = true; withMultimedia = true; withWebKit = true; };
    })
  ];
}
```

**Comment by vlaci** [comment]
Sweet! Thank you.
