### ISSUE TITLE
scipy fails to build

### ISSUE THREAD

**Issue by jethrokuan** [nix-community/poetry2nix#36]
I have a simple project here, and I'm trying to set it up to use with poetry2nix:

https://github.com/jethrokuan/esnn

The poetry.lock, shell.nix files can all be found there. The project only has 1 dependency: `scikitlearn`. In particular, `scipy` fails to build:

```
these derivations will be built:
  /nix/store/2msnz1cdh6kn7rp15acvrm53g4z9mh2h-python3.7-scipy-1.4.1.drv
  /nix/store/gny52v335dnwfy7v8g9ynfsry4z98zjf-python3.7-scikit-learn-0.22.1.drv
  /nix/store/vxsikfljvhvwi1v9vswkjlwgvhvb24jq-python3-3.7.6-env.drv
building '/nix/store/2msnz1cdh6kn7rp15acvrm53g4z9mh2h-python3.7-scipy-1.4.1.drv'...
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
unpacking sources
unpacking source archive /nix/store/jzrmjnhj56rdg13rqxylp3scxjjihr3v-scipy-1.4.1.tar.gz
source root is scipy-1.4.1
setting SOURCE_DATE_EPOCH to timestamp 1576697826 of file scipy-1.4.1/PKG-INFO
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
WARNING: The directory '/homeless-shelter/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5cb0750>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pybind11/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5cc8910>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pybind11/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5cc8b10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pybind11/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5cc8cd0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pybind11/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5cc8d90>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pybind11/
ERROR: Could not find a version that satisfies the requirement pybind11>=2.4.0 (from versions: none)
ERROR: No matching distribution found for pybind11>=2.4.0
Traceback (most recent call last):
  File "/nix/store/wa1pwr7lxg29z8b8f8880y13ql3d2l7z-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp0662_ho7', '--quiet', 'pybind11>=2.4.0']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 540, in <module>
    setup_package()
  File "setup.py", line 536, in setup_package
    setup(**metadata)
  File "/nix/store/kx73cf4x5y28i0pmlsfi155irxy547nh-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/distutils/core.py", line 128, in setup
    dist = setup(**new_attr)
  File "/nix/store/kx73cf4x5y28i0pmlsfi155irxy547nh-python3.7-numpy-1.18.1/lib/python3.7/site-packages/numpy/distutils/core.py", line 171, in setup
    return old_setup(**new_attr)
  File "/nix/store/wa1pwr7lxg29z8b8f8880y13ql3d2l7z-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/nix/store/wa1pwr7lxg29z8b8f8880y13ql3d2l7z-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/nix/store/wa1pwr7lxg29z8b8f8880y13ql3d2l7z-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "/nix/store/wa1pwr7lxg29z8b8f8880y13ql3d2l7z-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/nix/store/wa1pwr7lxg29z8b8f8880y13ql3d2l7z-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/nix/store/wa1pwr7lxg29z8b8f8880y13ql3d2l7z-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/nix/store/wa1pwr7lxg29z8b8f8880y13ql3d2l7z-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/nix/store/wa1pwr7lxg29z8b8f8880y13ql3d2l7z-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/nix/store/s7vw8y02cqzx8bnjxl4bkhlnwvz6ws1s-python3-3.7.6/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp0662_ho7', '--quiet', 'pybind11>=2.4.0']' returned non-zero exit status 1.
builder for '/nix/store/2msnz1cdh6kn7rp15acvrm53g4z9mh2h-python3.7-scipy-1.4.1.drv' failed with exit code 1
cannot build derivation '/nix/store/vxsikfljvhvwi1v9vswkjlwgvhvb24jq-python3-3.7.6-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/vxsikfljvhvwi1v9vswkjlwgvhvb24jq-python3-3.7.6-env.drv' failed
```

It seems to me pybind11 is missing from the default scipy overrides, but adding it there results in infinite recursion, am not sure what to do here.

**Comment by adisbladis** [comment]
It leads to infinite recursion because `pybind11` from nixpkgs (which you end up picking because `pybind11` is not in your poetry env) is depending on `scipy`.

Pushed the required overrides in 6032bb34b2ae320e7f1b7c5f4197dc36d9d61b66.

**Comment by jethrokuan** [comment]
Thanks for the quick fix!
