### ISSUE TITLE
Python scripts called from a parent python script do not have access to dependencies

### ISSUE THREAD

**Issue by danielfullmer** [nix-community/poetry2nix#373]
**Summary:**

Inside a `nix-shell` environment, a python script that executes another python script as a subprocess will fail if that subprocess tries to import any python dependencies provided by poetry.

**To reproduce:**

Create the following files.

Contents of `zz/foo.py`:
```python
import subprocess

def main():
    subprocess.run('bar')
```

Contents of `zz/bar.py`:
```python
import pydantic

def main():
    print('bar')
```

Contents of `pyproject.toml`:
```
[tool.poetry]
name = "zz"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [
    { include = "zz" }
]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
foo = 'zz.foo:main'
bar = 'zz.bar:main'
````

Contents of `shell.nix`:
```nix
{ pkgs ? import <nixpkgs> {} }:
let
  myAppEnv = pkgs.poetry2nix.mkPoetryEnv {
    projectDir = ./.;
    editablePackageSources = {
      my-app = ./zz;
    };
  };
in
pkgs.mkShell {
  buildInputs = [ myAppEnv pkgs.hello ];
}
```

Run the following:
```shell
$ poetry install  # To create poetry.lock file
$ nix-shell
$ foo
Traceback (most recent call last):
  File "/nix/store/ffl2ac5zjzjdzaqcjc13480mkrid4pyr-python3.9-poetry2nix-env-scripts/bin/.bar-wrapped", line 9, in <module>
    from zz.bar import main
  File "/homecache/danielrf/tmp/zz/zz/bar.py", line 1, in <module>
    import pydantic
ModuleNotFoundError: No module named 'pydantic'
```

So, the `bar` script does not have access to the `pydantic` dependency included in the `pyproject.toml`.

However, when using `poetry shell`, this does work correctly:
```
$ poetry shell
$ foo
bar
```

**Comment by danielfullmer** [comment]
I think I've found the issue.  These scripts are ultimately being wrapped by two separate layers, only one of which includes the poetry dependencies we need.
1) Outer layer `mkPoetryEnv` which uses `python.withPackages` including all the dependencies and scripts packages.
2) Inner layer `mkPoetryScriptsPackage` which uses`buildPythonPackage` inside `shell-scripts.nix`, but does not include any other dependencies.

As a result of (2), if we tried to use the output provided directly by `mkPoetryScriptsPackage { projectDir = ./.; }`, we end up with the same error of missing dependencies:
```
$ nix-build -E "(import <nixpkgs> {}).poetry2nix.mkPoetryScriptsPackage { projectDir = ./.; }"
$ ./result/bin/bar
Traceback (most recent call last):
  File "/nix/store/ffl2ac5zjzjdzaqcjc13480mkrid4pyr-python3.9-poetry2nix-env-scripts/bin/.bar-wrapped", line 9, in <module>
    from zz.bar import main
  File "/homecache/danielrf/tmp/zz/zz/bar.py", line 1, in <module>
    import pydantic
ModuleNotFoundError: No module named 'pydantic'
```

I believe the only reason the scripts normally work is because the scripts are wrapped again by `mkPoetryEnv`, which does include the dependencies we need.

I also believe the original issue is caused by the issue above, plus the fact that the wrapper provided by (2) overrides the PATH, so the script will then call python subprocesses using this PATH, where the scripts don't know how to find their own dependencies.
```shell
#! /nix/store/dpjnjrqbgbm8a5wvi1hya01vd8wyvsq4-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/nki9ywqzbvz68vr75kn2r7g1q84f5agy-python3-3.9.6/bin:/nix/store/ffl2ac5zjzjdzaqcjc13480mkrid4pyr-python3.9-poetry2nix-env-scripts/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/ffl2ac5zjzjdzaqcjc13480mkrid4pyr-python3.9-poetry2nix-env-scripts/bin/.bar-wrapped"  "$@"
```

It's not immediately clear to me what the correct way to fix this would be.  Presumably we'd like to have `mkPoetryScriptsPackage` also include its dependencies in the scripts wrappers. So, would `mkPoetryScriptsPackage` need to call `mkPoetryPackages`?
