### ISSUE TITLE
Unable to install pytest

### ISSUE THREAD

**Issue by robertodr** [nix-community/poetry2nix#41]
I am trying to install `pytest` in a shell, but the builder fails with:
```
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5cbaf50>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5c4f050>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
ERROR: Could not find a version that satisfies the requirement setuptools_scm>=3.4 (from versions: none)
ERROR: No matching distribution found for setuptools_scm>=3.4
Traceback (most recent call last):
  File "/nix/store/z6jd1l54n00wrw97l4payllgaypk41hx-python3.7-setuptools-42.0.2/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/nix/store/d89hv7fvmky59qqgzb1yiwagv34i1q75-python3-3.7.5/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/d89hv7fvmky59qqgzb1yiwagv34i1q75-python3-3.7.5/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp8tiivc0q', '--quiet', 'setuptools_scm>=3.4']' returned non-zero exit status 1.
```

The `pyproject.toml`:
```
[tool.poetry]
name = "example"
version = "0.1.0"
description = ""
authors = ["Roberto Di Remigio"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
The `shell.nix`:
```
with import (builtins.fetchGit {
  name = "nixpkgs-unstable-2020-01-06";
  url = "https://github.com/NixOS/nixpkgs-channels";
  ref = "nixpkgs-unstable";
  # `git ls-remote https://github.com/nixos/nixpkgs-channels nixpkgs-unstable`
  rev = "7e8454fb856573967a70f61116e15f879f2e3f6a";
}) {
};

let
  src = fetchFromGitHub {
    owner = "nix-community";
    repo = "poetry2nix";
    rev = "f1af96e2c5f4abcd1bbebbc370390edc0acfd84f";
    sha256 = "0phvbj7dg8pf82qa2519hy8lh0wpjhi5c7d46iv22pwhhhiiynkn";
  };
in
with import "${src.out}/overlay.nix" pkgs pkgs;
let
  pythonEnv = poetry2nix.mkPoetryEnv {
    python = python3;
    poetrylock = ./poetry.lock;
    overrides = [];
  };
in
  mkShell {
    name = "example";
    nativeBuildInputs = [
      pythonEnv
      poetry
    ];
  }
```

**Comment by adisbladis** [comment]
The problem here is that `pytest` requires a version of `setuptools-scm` that's newer than what's in Nixpkgs and since the dependency graph is incomplete (it doesn't include `setuptools-scm`) you end up with the version from Nixpkgs.

A simple fix is simply adding a correct version of `setuptools-scm` to your environment and manage that dependency yourself.

**Comment by adisbladis** [comment]
Closing because I don't know what `poetry2nix` could reasonably do given that we don't really know the setuptools-scm dependency specification ahead of time.

**Comment by adisbladis** [comment]
Also: Don't pass an empty list of overrides as that will make `poetry2nix` _not_ apply it's default overrides.

**Comment by robertodr** [comment]
> Also: Don't pass an empty list of overrides as that will make `poetry2nix` _not_ apply it's default overrides.

Thanks for the tip. My knowledge of Nix is shaky...

**Comment by robertodr** [comment]
> The problem here is that `pytest` requires a version of `setuptools-scm` that's newer than what's in Nixpkgs and since the dependency graph is incomplete (it doesn't include `setuptools-scm`) you end up with the version from Nixpkgs.
> 
> A simple fix is simply adding a correct version of `setuptools-scm` to your environment and manage that dependency yourself.

I've now added `setuptools-scm = "^3.4"` to my `pyproject.toml` and it worked. Thanks again!

**Comment by robertodr** [comment]
The trick of adding `setuptools-scm = "^3.4"` seems to have broken, sadly. I now get a different error:
```
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5cbe8d0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/toml/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5cbead0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/toml/
ERROR: Could not find a version that satisfies the requirement toml (from versions: none)
ERROR: No matching distribution found for toml
Traceback (most recent call last):
  File "/nix/store/z6jd1l54n00wrw97l4payllgaypk41hx-python3.7-setuptools-42.0.2/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/nix/store/d89hv7fvmky59qqgzb1yiwagv34i1q75-python3-3.7.5/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/d89hv7fvmky59qqgzb1yiwagv34i1q75-python3-3.7.5/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmptywcst48', '--quiet', 'toml']' returned non-zero exit status 1.
```
adding `toml = "0.10"` to `pyproject.toml` does not help. Same goes with the following addition:
```
setuptools-scm = { version = "^3.4", extras = ["toml"] }
```
Any clues?

**Comment by adisbladis** [comment]
While looking into this I found another bug which I fixed in 1ffabaa066d446ec3d8325160bf71cdad5c89d38.

Stupid question perhaps but did you run `poetry lock` after adding to `pyproject.toml`?

**Comment by robertodr** [comment]
That commit did it. Thank you! I needed to add:
```
setuptools-scm = { version = "^3.4", extras = ["toml"] }
```
to my `pyproject.toml`

**Comment by Shados** [comment]
@robertodr is this work-around still functioning for you? I have run into the same issue but I get an infinite recursion in Nix when attempting your solution...
