### ISSUE TITLE
Failure when installing sqlite-utils

### ISSUE THREAD

**Issue by rrrnld** [nix-community/poetry2nix#422]
Hi! I'm having a hard time trying to building the [poetry environment of this project](https://github.com/heyarne/listenbrainz-to-sqlite/blob/main/pyproject.toml) using `poetry2nix`. The problem seems to be a transitive dependency of `datasette`, `sqlite-utils`, which raises the following error:

```
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/kavw6gwwsilpzc98i76684xapkcvlhf6-sqlite-utils-3.17.1.tar.gz
source root is sqlite-utils-3.17.1
setting SOURCE_DATE_EPOCH to timestamp 1632344205 of file sqlite-utils-3.17.1/setup.cfg
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
no configure script, doing nothing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
Executing pipBuildPhase
Creating a wheel...
[33mWARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.[0m
Ignoring indexes: https://pypi.org/simple
Created temporary directory: /build/pip-ephem-wheel-cache-71xh6jse
Created temporary directory: /build/pip-req-tracker-2unm3542
Initialized build tracking at /build/pip-req-tracker-2unm3542
Created build tracker: /build/pip-req-tracker-2unm3542
Entered build tracker: /build/pip-req-tracker-2unm3542
Created temporary directory: /build/pip-wheel-z6_g1fuv
Processing /build/sqlite-utils-3.17.1
  Created temporary directory: /build/pip-req-build-kus9xm41
  Added file:///build/sqlite-utils-3.17.1 to build tracker '/build/pip-req-tracker-2unm3542'
    Running setup.py (path:/build/pip-req-build-kus9xm41/setup.py) egg_info for package from file:///build/sqlite-utils-3.17.1
    Created temporary directory: /build/pip-pip-egg-info-ipn3ad5r
    Running command python setup.py egg_info
    WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff5d72f10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pytest-runner/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff5d72550>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pytest-runner/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff5d72100>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pytest-runner/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff6aa9a90>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pytest-runner/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff5d12250>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pytest-runner/
    ERROR: Could not find a version that satisfies the requirement pytest-runner (from versions: none)
    ERROR: No matching distribution found for pytest-runner
    Traceback (most recent call last):
      File "/nix/store/krd4n1rq01nwqrw6xbrynq58420fxd6w-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/installer.py", line 75, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmpkqezxzt9', '--quiet', 'pytest-runner']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/build/pip-req-build-kus9xm41/setup.py", line 16, in <module>
        setup(
      File "/nix/store/krd4n1rq01nwqrw6xbrynq58420fxd6w-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "/nix/store/krd4n1rq01nwqrw6xbrynq58420fxd6w-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/nix/store/krd4n1rq01nwqrw6xbrynq58420fxd6w-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/dist.py", line 785, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/nix/store/krd4n1rq01nwqrw6xbrynq58420fxd6w-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 766, in resolve
        dist = best[req.key] = env.best_match(
      File "/nix/store/krd4n1rq01nwqrw6xbrynq58420fxd6w-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1051, in best_match
        return self.obtain(req, installer)
      File "/nix/store/krd4n1rq01nwqrw6xbrynq58420fxd6w-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1063, in obtain
        return installer(requirement)
      File "/nix/store/krd4n1rq01nwqrw6xbrynq58420fxd6w-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/dist.py", line 844, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/nix/store/krd4n1rq01nwqrw6xbrynq58420fxd6w-python3.9-setuptools-57.2.0/lib/python3.9/site-packages/setuptools/installer.py", line 77, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['/nix/store/97w52ckcjnfiz89h3lh7zf1kysgfm2s8-python3-3.9.6/bin/python3.9', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmpkqezxzt9', '--quiet', 'pytest-runner']' returned non-zero exit status 1.
[31mERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.[0m
Exception information:
Traceback (most recent call last):
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/commands/wheel.py", line 155, in run
    requirement_set = resolver.resolve(
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 482, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 555, in prepare_metadata
    self.metadata_directory = self._generate_metadata()
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 530, in _generate_metadata
    return generate_metadata_legacy(
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 70, in generate_metadata
    call_subprocess(
  File "/nix/store/z5397z0vyinkcr4hgbvpyxh9qsnj764p-python3.9-pip-20.2.4/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removed file:///build/sqlite-utils-3.17.1 from build tracker '/build/pip-req-tracker-2unm3542'
Removed build tracker: '/build/pip-req-tracker-2unm3542'
```

My mental model of how `poetry2nix` works is this: Poetry does unambiguous dependency resolution for my project and writes a way to reproduce this to its lockfile. `poetry2nix` converts this lockfile into something that is usable by Nix. How can a package raise an error if the environment seems to work fine using the various `poetry …` commands?

And another question: How can I build the python application without including the development dependencies (in this case `datasette` and related plugins)?

Thanks for any help!

**Comment by cpcloud** [comment]
> How can a package raise an error if the environment seems to work fine using the various poetry … commands

There are a number of other things that happen after solving that can cause this to happen. Here are two that I can think of.

1. `poetry` often (reasonably so) contacts the internet to do its job. `nix` generally does not allow a derivation to do that. This is a little difficult to see in your traceback, but these lines give it away:

```
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7ffff5d12250>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/pytest-runner/
```

2. If a package has external dependencies like an external C library then it's entirely possible for a user to have installed that C library using their OS package manager and then run `poetry $WHATEVER` and have the environment work.

`poetry2nix` requires users you to explicitly state that a package depends on another derivation that isn't a python package, such as `jq` (for example), because `nix` requires this.

> How can I build the python application without including the development dependencies (in this case datasette and related plugins)?

How are you determining that the application includes everything? `mkPoetryApplication` should behave this way by default. I use `poetry2nix` for https://github.com/cpcloud/protoletariat which depends on black, isort and number of other development dependencies (just as `datasette` is for your package), and the full dependency closure is:

```
❯ nix build -L '.#protoletariat' && nix path-info -Shr -L '.#protoletariat'
/nix/store/qbdsd82q5fyr0v31cvfxda0n0h7jh03g-libunistring-0.9.10                    1.6M
/nix/store/scz4zbxirykss3hh5iahgl39wk9wpaps-libidn2-2.3.2                          1.8M
/nix/store/563528481rvhc5kxwipjmg6rqrl95mdx-glibc-2.33-56                         31.6M
/nix/store/0q6ld4vi2vaf3nk83z1rdb39yv2bjvla-gdbm-1.20                             32.3M
/nix/store/yilda176cq33hbv240mqzkf6ks6r9b1p-ncurses-6.2                           35.0M
/nix/store/2v3nbpa6vhj3x9d5cq35p7bzf0dv2jl3-readline-6.3p08                       35.4M
/nix/store/2zz2l3j07h9bkvdmxhxinj2rcjy3cdh7-zlib-1.2.11                           31.7M
/nix/store/30q5xa4pfbvic54nh68qn86w6kjki66i-sqlite-3.36.0                         33.1M
/nix/store/54q7szc4fhiyh7pmjh9x2w90f18m5s6f-libffi-3.4.2                          31.7M
/nix/store/6kgfmzx90c1a6afqnbkz6qprkzss476k-mime-types-9                          64.3K
/nix/store/7wxhajvlpndhmcwrpc73sl959yb7jzbr-tzdata-2021c                           2.0M
/nix/store/a54wrar1jym1d8yvlijq0l2gghmy8szz-bash-5.1-p12                          33.1M
/nix/store/afirirs0ajv8adpjc2554f8scbxdh4dh-xz-5.2.5                              32.1M
/nix/store/b2rbbn5kpg8bxrg7n82m4q4wdcz2fyy7-openssl-1.1.1l                        35.6M
/nix/store/cgg7sv3aa40mksfrm44rfifcgprgd25v-expat-2.4.1                           31.9M
/nix/store/ckqhvpa7mg8181pfhd4gb1k834npjm89-bzip2-1.0.6.0.2                       31.7M
/nix/store/bcbiv6wc018v7lpy6yw43n7z6k7172qv-python3-3.10.0                       135.0M
/nix/store/0bm5yiq7q3y3m14zrwzlxzgijpgjwilz-python3.10-click-8.0.3               135.6M
/nix/store/7kzqyqrhcj9c6vc0qydh2fa6izis9y26-python3.10-protobuf-3.19.1           136.1M
/nix/store/sy466yli3wq9cs0aplfri1nffqg44ni6-python3.10-setuptools-57.2.0         138.6M
/nix/store/f6k01b8b74ypsqyi0r4hh3fa16zgi54b-python3.10-protoletariat-0.7.0       140.4M
```

Only the runtime dependencies are included. If you're seeing something else then please open a specific issue about that.

**Comment by cpcloud** [comment]
The solution for the first problem of "how do I install a thing that contacts the internet?" usually involves telling that package how to find what it's looking for using one of nix functions like `fetchurl`/`fetchFromGitHub` etc.

These functions tell nix (roughly) "hey, here's a hash of this package, don't worry about the fact that I'm contacting the internet and check that the downloaded stuff matches the hash I specified"

There are lots of examples of `fetchFromGitHub`/`fetchurl` in [NixOS/nixpkgs](https://github.com/NixOS/nixpkgs).
