### ISSUE TITLE
mkPoetryEnv does not create egg-info metadata correctly

### ISSUE THREAD

**Issue by schlarpc** [nix-community/poetry2nix#616]
### Describe the issue

When executing a package built with `mkPoetryApplication`, `importlib.metadata` is able to access the built package's metadata such as the version. When operating under `mkPoetryEnv`, the metadata is not found by Python. This appears to be caused by misnaming of `.egg-info` metadata files.

#### Relevant files

- `shell.nix`
```
{ pkgs ? import <nixpkgs> {} }:
let
  myAppEnv = pkgs.poetry2nix.mkPoetryEnv {
    projectDir = ./.;
    editablePackageSources = {
      p2n-egginfo = ./src;
    };
  };
in myAppEnv.env
```

- `default.nix`
```
{ pkgs ? import <nixpkgs> {} }:
let
  myApp = pkgs.poetry2nix.mkPoetryApplication {
    projectDir = ./.;
  };
in myApp
```

- `pyproject.toml`
```
[tool.poetry]
name = "p2n-egginfo"
version = "0.1.0"
description = ""
authors = ["Chaz Schlarp <schlarpc@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
p2n-egginfo-test = "p2n_egginfo:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

- `poetry.lock`
```
package = []

[metadata]
lock-version = "1.1"
python-versions = "^3.9"
content-hash = "ce2aa767160f871dd3652615ba0a0dceb7733d62eb8cb4665b87f30a562e3adf"

[metadata.files]
```

- `src/p2n_egginfo/__init__.py`
```
import importlib.metadata

def main():
    print(importlib.metadata.version('p2n_egginfo'))
```

#### Explanation

Under `mkPythonApplication`, accessing the package metadata works fine:

```
$ nix-build; and ./result/bin/p2n-egginfo-test
/nix/store/qr6ijk5ck6d1rsi73fci9jdd1s1jjc0m-python3.9-p2n-egginfo-0.1.0
0.1.0
```

But under `mkPoetryEnv`, it fails. 

```
$ nix-shell --run 'p2n-egginfo-test'
Traceback (most recent call last):
  File "/nix/store/dx25wvlwqi828rpjk5z7h5ddrvp89bab-python3.9-poetry2nix-env-scripts/bin/.p2n-egginfo-test-wrapped", line 13, in <module>
    sys.exit(main())
  File "/home/schlarpc/p2n-egginfo/src/p2n_egginfo/__init__.py", line 4, in main
    print(importlib.metadata.version('p2n_egginfo'))
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/importlib/metadata.py", line 569, in version
    return distribution(distribution_name).version
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/importlib/metadata.py", line 542, in distribution
    return Distribution.from_name(distribution_name)
  File "/nix/store/hym1n0ygqp9wcm7pxn4sfrql3fg7xa09-python3-3.9.12/lib/python3.9/importlib/metadata.py", line 196, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: p2n_egginfo
```

My initial thought was that I was configuring the attributes names in `editablePackageSources` incorrectly, but it doesn't seem like they're actually used for anything. Regardless, this same issue also occurs when `editablePackageSources` is unset. 

Comparing the runtime environment of the two, you can see that the `mkPoetryEnv` build is using `p2n-egginfo.egg-info` for metadata, while `mkPoetryApplication` is using `p2n_egginfo-0.1.0.dist-info`:

```
$ ls (dirname (nix-shell --run 'which p2n-egginfo-test'))/../lib/python3.9/site-packages
README.txt
__pycache__
_distutils_hack
_sysconfigdata__linux_x86_64-linux-gnu.py
distutils-precedence.pth
p2n-egginfo.egg-info
pkg_resources
poetry2nix-editable.pth
setuptools
setuptools-61.2.0.post0.dist-info
sitecustomize.py
```

```
$ ls result/lib/python3.9/site-packages/
p2n_egginfo
p2n_egginfo-0.1.0.dist-info
```

It seems that Python expects the `.egg-info` to match the module name (with underscores). When the `.egg-info` is named the same as the module name, accessing the metadata succeeds:

```
$ nix-shell --run 'p2n-egginfo-test'
0.1.0
```

I've managed to make this work without modifying `poetry2nix` by adding a hacky entry to `mkPoetryEnv`'s `extraPackages` which adds an extra `.egg-info` based on the directories in `./src`:

```
{ pkgs ? import <nixpkgs> {} }:
let
    pyProject = builtins.fromTOML (builtins.readFile (./. + "/pyproject.toml"));
    pkgInfoFields = {
      Metadata-Version = "2.1";
      Name = pyProject.tool.poetry.name;
      Version = pyProject.tool.poetry.version;
      Summary = pyProject.tool.poetry.description;
    };
    pkgInfoFile = with pkgs.lib.generators; (
      builtins.toFile "${pyProject.tool.poetry.name}-PKG-INFO"
        (toKeyValue { mkKeyValue = mkKeyValueDefault { } ": "; } pkgInfoFields)
    );
    moduleNames = (
      pkgs.lib.attrNames
        (
          pkgs.lib.filterAttrs
            (n: v: v == "directory")
            (builtins.readDir ./src)
        )
    );
    editableEggInfoFix = ps:
      (ps.toPythonModule (
        pkgs.runCommand "editable-egg-info-fix" { } ''
          mkdir -p "$out/${ps.python.sitePackages}"
          cd "$out/${ps.python.sitePackages}"
          ${
            pkgs.lib.concatMapStringsSep
            "\n"
            (pkg: ''mkdir "${pkg}.egg-info"; ln -s "${pkgInfoFile}" "${pkg}.egg-info/PKG-INFO"'')
            moduleNames
          }
        ''));
  myAppEnv = pkgs.poetry2nix.mkPoetryEnv {
    projectDir = ./.;
    editablePackageSources = {
      p2n-egginfo = ./src;
    };
    extraPackages = (ps: [ (editableEggInfoFix ps) ]);
  };
in myAppEnv.env
```

```
$ ls (dirname (nix-shell --run 'which p2n-egginfo-test'))/../lib/python3.9/site-packages
README.txt
__pycache__
_distutils_hack
_sysconfigdata__linux_x86_64-linux-gnu.py
distutils-precedence.pth
p2n-egginfo.egg-info
p2n_egginfo.egg-info
pkg_resources
poetry2nix-editable.pth
setuptools
setuptools-61.2.0.post0.dist-info
sitecustomize.py
```

**Comment by paraseba** [comment]
Is there a more definitive solution to this issue?
