### ISSUE TITLE
exceptiongroup 1.0.0rc8 missing flit_scm module

### ISSUE THREAD

**Issue by l0b0** [nix-community/poetry2nix#693]
### Describe the issue

Building the below (from [this project](https://github.com/linz/oidc-provider)) using latest nixpkgs results in the following error:

> ModuleNotFoundError: No module named 'flit_scm'

### Additional context

- [`shell.nix`](https://github.com/linz/oidc-provider/blob/3a3f5384bd6ecc18c1ded1736a02ea0eb29877af/shell.nix)
- [`pyproject.toml`](https://github.com/linz/oidc-provider/blob/3a3f5384bd6ecc18c1ded1736a02ea0eb29877af/pyproject.toml)
- [`poetry.lock`](https://github.com/linz/oidc-provider/blob/3a3f5384bd6ecc18c1ded1736a02ea0eb29877af/poetry.lock)

**Comment by dmizelle** [comment]
I just ran into this myself. It looks like that `flit` isn't being included here by default.

I am like an intermediate nix user, but ended up getting around it by passing `extraPackages` to `poetry2nix.mkPoetryEnv` like so:

```nix
  outputs = { self, nixpkgs, flake-utils, poetry2nix }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config = { allowBroken = true; };
          overlays = [ poetry2nix.overlay ];
        };
      in {
        devShell = pkgs.mkShell {
          nativeBuildInputs = [ pkgs.bashInteractive ];
          buildInputs = with pkgs; [
            # [SNIP]
            (pkgs.poetry2nix.mkPoetryEnv {
              projectDir = ./.;
              preferWheels = true;
              extraPackages = (ps: [ pythonPackages.flit ]); # <------
            })
          ];
        };
      })
```

**Comment by l0b0** [comment]
I've tried two similar things and get the same result:

```
extraPackages = (ps: [ pkgs.python310Packages.flit ]);
```

and

```
exceptiongroup = super.exceptiongroup.overridePythonAttrs (
  old: {
    nativeBuildInputs = old.nativeBuildInputs or [ ] ++ [ self.flit ];
  }
);
```

**Comment by l0b0** [comment]
It looks like what's missing is deciphering what `flitBuildHook` evaluates to, and including that. AFAICT this requires running `tools/find-build-systems.py`, which I can't see referenced *anywhere else* in the repo. I tried to `nix-build` and run it with the resulting Python, but no go:

```console
$ nix-build
/nix/store/wq9z8rvdyyrpcs2sx6406g84df1dvv7r-python3-3.9.13-env
/nix/store/13m7a00vsx0ybm73lnzzqsgs57m2cr56-poetry2nix-flamegraph
/nix/store/c0yhkfmz2ym3937r5j3bjngxfrllnkyp-py2-astparse
$ result/bin/python ./find-build-systems.py foo
Traceback (most recent call last):
  File "/home/victor/dev/poetry2nix/tools/./find-build-systems.py", line 167, in <module>
    main()
  File "/home/victor/dev/poetry2nix/tools/./find-build-systems.py", line 155, in main
    build_systems = get_build_systems(known_systems)
  File "/home/victor/dev/poetry2nix/tools/./find-build-systems.py", line 122, in get_build_systems
    futures = {
  File "/home/victor/dev/poetry2nix/tools/./find-build-systems.py", line 122, in <dictcomp>
    futures = {
  File "/home/victor/dev/poetry2nix/tools/./find-build-systems.py", line 87, in yield_drvs
    p = subprocess.Popen(
  File "/nix/store/rdm31z7s8m6aaydnq949g2zql4wixsgd-python3-3.9.13/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/rdm31z7s8m6aaydnq949g2zql4wixsgd-python3-3.9.13/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nix-eval-jobs'
```

**Comment by considerate** [comment]
I solved this issue with the following overrides:
```nix
final.poetry2nix.overrides.withDefaults (self: super: {
  flit-scm = self.callPackage ./flit-scm.nix { };
  exceptiongroup = super.exceptiongroup.overridePythonAttrs (old: {
    nativeBuildInputs = old.nativeBuildInputs ++ [
      self.flit-scm
    ];
  });
})
```
where `flit-scm.nix` is
```nix
{ buildPythonPackage
, fetchPypi
, flit-core
, flitBuildHook
, setuptools-scm
}:
buildPythonPackage {
  pname = "flit-scm";
  version = "1.7.0";
  format = "flit";
  src = fetchPypi {
    pname = "flit_scm";
    version = "1.7.0";
    sha256 = "961bd6fb24f31bba75333c234145fff88e6de0a90fc0f7e5e7c79deca69f6bb2";
  };
  nativeBuildInputs = [
    flit-core
    flitBuildHook
    setuptools-scm
  ];
  pythonImportsCheck = [ "flit_scm" ];
}

```

**Comment by yajo** [comment]
I guess flit-scm should be published to nixpkgs and then added as known build engines. Isn't it?

**Comment by Jimlinz** [comment]
Ran into similar problem trying to bump [cattrs 22.2.0](https://github.com/linz/geostore/pull/2192).

**Comment by l0b0** [comment]
@yajo flit-scm is not in 22.05 yet, but a [PR to introduce it to the master branch](https://github.com/NixOS/nixpkgs/pull/197757) was added just 11 hours ago. Not sure when/if it will be promoted to stable.

**Comment by yajo** [comment]
Seems to be merged now.

**Comment by adisbladis** [comment]
> Seems to be merged now.

I also backported it to 22.05.

**Comment by cpcloud** [comment]
Thanks all, this is fixed in master!
