### ISSUE TITLE
watchfiles: ModuleNotFoundError: No module named 'maturin'

### ISSUE THREAD

**Issue by rszamszur** [nix-community/poetry2nix#731]
### Describe the issue

The build of watchfiles fails with the following message: `ModuleNotFoundError: No module named 'maturin'`. 

Usually, I'm able to solve build issues with overlay/overrides. However, since watchfiles is mix language package, it's uncharted waters for me. 

<details>
  <summary><b>Traceback</b></summary>
 
  ```bash
these 2 derivations will be built:
  /nix/store/rk8jym8szngb0cgz5k7a8lvnv812pp8f-python3.9-watchfiles-0.17.0.drv
  /nix/store/xqwdwhyj1lqww4yn4vrb843pw6fn0rcb-python3-3.9.13-env.drv
building '/nix/store/rk8jym8szngb0cgz5k7a8lvnv812pp8f-python3.9-watchfiles-0.17.0.drv'...
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhase
Using pipShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
unpacking sources
unpacking source archive /nix/store/gz8grsv8d39f2csi2l8vkpwzyj4av4ll-watchfiles-0.17.0.tar.gz
source root is watchfiles-0.17.0
setting SOURCE_DATE_EPOCH to timestamp 1662906498 of file watchfiles-0.17.0/watchfiles/version.py
patching sources
Removing path dependencies
Finished removing path dependencies
Removing git dependencies
Finished removing git dependencies
configuring
no configure script, doing nothing
building
Executing pipBuildPhase
Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Processing /build/watchfiles-0.17.0
  Running command Preparing metadata (pyproject.toml)
  Preparing metadata (pyproject.toml) ... done
ERROR: Exception:
Traceback (most recent call last):
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/commands/wheel.py", line 145, in run
    requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 506, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 291, in __init__
    super().__init__(
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 428, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 497, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 526, in prepare_metadata
    self.metadata_directory = generate_metadata(
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_internal/utils/misc.py", line 706, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 188, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/nix/store/vl15w3q3ck77gk0yi03abi3xghxhlwgw-python3-3.9.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'maturin'


error: builder for '/nix/store/rk8jym8szngb0cgz5k7a8lvnv812pp8f-python3.9-watchfiles-0.17.0.drv' failed with exit code 2;
       last 10 log lines:
       >   File "/nix/store/k881569hjxhyv4xi4vgqlfxcyc2qw50r-python3.9-pip-22.1.2/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 89, in _build_backend
       >     obj = import_module(mod_path)
       >   File "/nix/store/vl15w3q3ck77gk0yi03abi3xghxhlwgw-python3-3.9.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
       >     return _bootstrap._gcd_import(name[level:], package, level)
       >   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
       >   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
       >   File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
       > ModuleNotFoundError: No module named 'maturin'
       > 
       > 
       For full logs, run 'nix log /nix/store/rk8jym8szngb0cgz5k7a8lvnv812pp8f-python3.9-watchfiles-0.17.0.drv'.
error: 1 dependencies of derivation '/nix/store/xqwdwhyj1lqww4yn4vrb843pw6fn0rcb-python3-3.9.13-env.drv' failed to build

  ```
</details>

### To reproduce

<details>
  <summary><b>shell.nix</b></summary>

  ```nix
  { pkgs ? import
      (builtins.fetchTarball {
        name = "22.05";
        url = "https://github.com/NixOS/nixpkgs/archive/b542cc75fa03a3a29350d4c3b69739e946268a93.tar.gz";
        sha256 = "0pdv4vi44xsdrx845dih8igryy8scidkgg9nw2gzf8gpgxj44rgr";
      })
      { }
  }:
  let
    src = pkgs.fetchFromGitHub {
      owner = "nix-community";
      repo = "poetry2nix";
      rev = "b470167f368852532a4e0fae5052b172966bf1da";
      sha256 = "sha256-o///tZjSHbKFvcTsF18Hr2mwVuN85TQQZQzzoRgj+c8=";
    };
    poetry2nix = import "${src.out}/default.nix" { inherit pkgs; };
  
    poetryEnv = poetry2nix.mkPoetryEnv {
      python = pkgs.python3;
      projectDir = ./.;
      pyproject = ./pyproject.toml;
      poetrylock = ./poetry.lock;
    };
  in
  poetryEnv.env
  ```
</details>

<details>
  <summary><b>pyproject.toml</b></summary>

  ```toml
  [tool.poetry]
  name = "John Doe"
  version = "0.1.0"
  description = ""
  authors = []
  
  [tool.poetry.dependencies]
  python = "^3.9"
  watchfiles = "0.17.0"
  
  [tool.poetry.dev-dependencies]
  
  [build-system]
  requires = ["poetry-core>=1.0.0"]
  build-backend = "poetry.core.masonry.api"
  ```
</details>

<details>
  <summary><b>poetry.lock</b></summary>

  ```
  [[package]]
  name = "anyio"
  version = "3.6.1"
  description = "High level compatibility layer for multiple asynchronous event loop implementations"
  category = "main"
  optional = false
  python-versions = ">=3.6.2"
  
  [package.dependencies]
  idna = ">=2.8"
  sniffio = ">=1.1"
  
  [package.extras]
  doc = ["packaging", "sphinx-rtd-theme", "sphinx-autodoc-typehints (>=1.2.0)"]
  test = ["coverage[toml] (>=4.5)", "hypothesis (>=4.0)", "pytest (>=7.0)", "pytest-mock (>=3.6.1)", "trustme", "contextlib2", "uvloop (<0.15)", "mock (>=4)", "uvloop (>=0.15)"]
  trio = ["trio (>=0.16)"]
  
  [[package]]
  name = "idna"
  version = "3.4"
  description = "Internationalized Domain Names in Applications (IDNA)"
  category = "main"
  optional = false
  python-versions = ">=3.5"
  
  [[package]]
  name = "sniffio"
  version = "1.3.0"
  description = "Sniff out which async library your code is running under"
  category = "main"
  optional = false
  python-versions = ">=3.7"
  
  [[package]]
  name = "watchfiles"
  version = "0.17.0"
  description = "Simple, modern and high performance file watching and code reload in python."
  category = "main"
  optional = false
  python-versions = ">=3.7"
  
  [package.dependencies]
  anyio = ">=3.0.0,<4"
  
  [metadata]
  lock-version = "1.1"
  python-versions = "^3.9"
  content-hash = "778f3eb8172aaf41213f2ccd46e1298fad9112463b9670d7f9e9e02f210bf787"
  
  [metadata.files]
  anyio = [
      {file = "anyio-3.6.1-py3-none-any.whl", hash = "sha256:cb29b9c70620506a9a8f87a309591713446953302d7d995344d0d7c6c0c9a7be"},
      {file = "anyio-3.6.1.tar.gz", hash = "sha256:413adf95f93886e442aea925f3ee43baa5a765a64a0f52c6081894f9992fdd0b"},
  ]
  idna = [
      {file = "idna-3.4-py3-none-any.whl", hash = "sha256:90b77e79eaa3eba6de819a0c442c0b4ceefc341a7a2ab77d7562bf49f425c5c2"},
      {file = "idna-3.4.tar.gz", hash = "sha256:814f528e8dead7d329833b91c5faa87d60bf71824cd12a7530b5526063d02cb4"},
  ]
  sniffio = [
      {file = "sniffio-1.3.0-py3-none-any.whl", hash = "sha256:eecefdce1e5bbfb7ad2eeaabf7c1eeb404d7757c379bd1f7e5cce9d8bf425384"},
      {file = "sniffio-1.3.0.tar.gz", hash = "sha256:e60305c5e5d314f5389259b7f22aaa33d8f7dee49763119234af3755c55b9101"},
  ]
  watchfiles = [
      {file = "watchfiles-0.17.0-cp37-abi3-macosx_10_7_x86_64.whl", hash = "sha256:c7e1ffbd03cbcb46d1b7833e10e7d6b678ab083b4e4b80db06cfff5baca3c93f"},
      {file = "watchfiles-0.17.0-cp37-abi3-macosx_11_0_arm64.whl", hash = "sha256:539bcdb55a487126776c9d8c011094214d1df3f9a2321a6c0b1583197309405a"},
      {file = "watchfiles-0.17.0-cp37-abi3-manylinux_2_12_i686.manylinux2010_i686.whl", hash = "sha256:00e5f307a58752ec1478eeb738863544bde21cc7a2728bd1c216060406bde9c1"},
      {file = "watchfiles-0.17.0-cp37-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.whl", hash = "sha256:92675f379a9d5adbc6a52179f3e39aa56944c6eecb80384608fff2ed2619103a"},
      {file = "watchfiles-0.17.0-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:1dd1e3181ad5d83ca35e9147c72e24f39437fcdf570c9cdc532016399fb62957"},
      {file = "watchfiles-0.17.0-cp37-abi3-manylinux_2_17_armv7l.manylinux2014_armv7l.whl", hash = "sha256:204950f1d6083539af5c8b7d4f5f8039c3ce36fa692da12d9743448f3199cb15"},
      {file = "watchfiles-0.17.0-cp37-abi3-musllinux_1_1_aarch64.whl", hash = "sha256:4056398d8f6d4972fe0918707b59d4cb84470c91d3c37f0e11e5a66c2a598760"},
      {file = "watchfiles-0.17.0-cp37-abi3-musllinux_1_1_x86_64.whl", hash = "sha256:ffff3418dc753a2aed2d00200a4daeaac295c40458f8012836a65555f288be8b"},
      {file = "watchfiles-0.17.0-cp37-abi3-win32.whl", hash = "sha256:b5c334cd3bc88aa4a8a1e08ec9f702b63c947211275defdc2dd79dc037fcb500"},
      {file = "watchfiles-0.17.0-cp37-abi3-win_amd64.whl", hash = "sha256:53a2faeb121bc51bb6b960984f46901227e2e2475acc5a8d4c905a600436752d"},
      {file = "watchfiles-0.17.0-cp37-abi3-win_arm64.whl", hash = "sha256:58dc3140dcf02a8aa76464a77a093016f10e89306fec21a4814922a64f3e8b9f"},
      {file = "watchfiles-0.17.0-pp38-pypy38_pp73-macosx_10_7_x86_64.whl", hash = "sha256:adcf15ecc2182ea9d2358c1a8c2b53203c3909484918776929b7bbe205522c0e"},
      {file = "watchfiles-0.17.0-pp38-pypy38_pp73-manylinux_2_12_x86_64.manylinux2010_x86_64.whl", hash = "sha256:afd35a1bd3b9e68efe384ae7538481ae725597feb66f56f4bd23ecdbda726da0"},
      {file = "watchfiles-0.17.0-pp38-pypy38_pp73-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:ad2bdcae4c0f07ca6c090f5a2c30188cc6edba011b45e7c96eb1896648092367"},
      {file = "watchfiles-0.17.0-pp39-pypy39_pp73-macosx_10_7_x86_64.whl", hash = "sha256:a53cb6c06e5c1f216c792fbb432ce315239d432cb8b68d508547100939ec0399"},
      {file = "watchfiles-0.17.0-pp39-pypy39_pp73-manylinux_2_12_x86_64.manylinux2010_x86_64.whl", hash = "sha256:6a3d6c699f3ce238dfa90bcef501f331a69b0d9b076f14459ed8eab26ba2f4cf"},
      {file = "watchfiles-0.17.0-pp39-pypy39_pp73-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:a7f4271af86569bdbf131dd5c7c121c45d0ed194f3c88b88326e48a3b6a2db12"},
      {file = "watchfiles-0.17.0.tar.gz", hash = "sha256:ae7c57ef920589a40270d5ef3216d693f4e6f8864d8fc8b6cb7885ca98ad2a61"},
  ]
  ```
</details>

###  Investigation/Tried

 1. Using  `preferWheels = true;`  yields the same result.

<details>
  <summary>2. Easiest override I can think of</summary>

  ```nix
      overrides = poetry2nix.overrides.withDefaults (self: super: {
        watchfiles = super.watchfiles.overridePythonAttrs (old: {
          buildInputs = old.buildInputs or [ ] ++ [ pkgs.maturin ];
        });
      });
  ```
</details>

<details>
  <summary>3. Adding rustc and cargo to the nativeBuildInputs</summary>

  ```nix
     overrides = poetry2nix.overrides.withDefaults (self: super: {
      watchfiles = super.watchfiles.overridePythonAttrs (old: {
        nativeBuildInputs = old.nativeBuildInputs or [ ] ++ [ 
          self.setuptools-rust 
          pkgs.rustPlatform.cargoSetupHook
          pkgs.rustPlatform.rust.cargo
          pkgs.rustPlatform.rust.rustc
        ];
      });
    });

  ```

Yields:
```shell
unpacking source archive /nix/store/gz8grsv8d39f2csi2l8vkpwzyj4av4ll-watchfiles-0.17.0.tar.gz
source root is watchfiles-0.17.0
Executing cargoSetupPostUnpackHook
unpacking source archive 
do not know how to unpack source archive 
error: builder for '/nix/store/7ggg9fdny0v9q8jlc4g551p7p6p4bwsv-python3.9-watchfiles-0.17.0.drv' failed with exit code 1;
       last 10 log lines:
       > Using pipInstallPhase
       > Sourcing python-imports-check-hook.sh
       > Using pythonImportsCheckPhase
       > Sourcing python-namespaces-hook
       > unpacking sources
       > unpacking source archive /nix/store/gz8grsv8d39f2csi2l8vkpwzyj4av4ll-watchfiles-0.17.0.tar.gz
       > source root is watchfiles-0.17.0
       > Executing cargoSetupPostUnpackHook
       > unpacking source archive
       > do not know how to unpack source archive
       For full logs, run 'nix log /nix/store/7ggg9fdny0v9q8jlc4g551p7p6p4bwsv-python3.9-watchfiles-0.17.0.drv'.
error: 1 dependencies of derivation '/nix/store/4zd4z275bxl421x1iyfy9zlr9f66zkmk-python3-3.9.13-env.drv' failed to build

```

</details>

Finally, after inspiring with:
* https://github.com/nix-community/poetry2nix/issues/30
* https://github.com/nix-community/poetry2nix/pull/592
* https://github.com/nix-community/poetry2nix/pull/579
* https://github.com/NixOS/nixpkgs/blob/nixos-22.05/pkgs/development/python-modules/watchfiles/default.nix

<details>
  <summary>I've tried doing something similar:</summary>

```nix
    overrides = poetry2nix.overrides.withDefaults (self: super: {
      watchfiles =
        let
          getCargoHash = version: {
            "0.17.0" = "0000000000000000000000000000000000000000000000000000";
          }.${version} or null;
        in
        super.watchfiles.overridePythonAttrs (old: {
          cargoDeps = pkgs.rustPlatform.fetchCargoTarball {
            inherit (old) src;
            name = "${old.pname}-${old.version}";
            sha256 = getCargoHash old.version;
          };
          nativeBuildInputs = old.nativeBuildInputs or [ ] ++ [
            self.setuptools-rust
          ] ++ (with pkgs.rustPlatform; [
            cargoSetupHook
            rust.cargo
            rust.rustc
          ]);
        });
    });

```

Above yields:
```shell
building '/nix/store/4mqcn16dlpyjdy1hraz5a335apqy41j2-watchfiles-0.17.0-vendor.tar.gz.drv'...
unpacking sources
unpacking source archive /nix/store/gz8grsv8d39f2csi2l8vkpwzyj4av4ll-watchfiles-0.17.0.tar.gz
source root is watchfiles-0.17.0
setting SOURCE_DATE_EPOCH to timestamp 1662906498 of file watchfiles-0.17.0/watchfiles/version.py
patching sources
configuring
no configure script, doing nothing
building

ERROR: The Cargo.lock file doesn't exist

Cargo.lock is needed to make sure that cargoHash/cargoSha256 doesn't change
when the registry is updated.

error: builder for '/nix/store/4mqcn16dlpyjdy1hraz5a335apqy41j2-watchfiles-0.17.0-vendor.tar.gz.drv' failed with exit code 1;
       last 10 log lines:
       > patching sources
       > configuring
       > no configure script, doing nothing
       > building
       >
       > ERROR: The Cargo.lock file doesn't exist
       >
       > Cargo.lock is needed to make sure that cargoHash/cargoSha256 doesn't change
       > when the registry is updated.
       >
       For full logs, run 'nix log /nix/store/4mqcn16dlpyjdy1hraz5a335apqy41j2-watchfiles-0.17.0-vendor.tar.gz.drv'.
error: 1 dependencies of derivation '/nix/store/ajakp1zjiwysgz8w01b9nqd5nf10m73w-python3.9-watchfiles-0.17.0.drv' failed to build
error: 1 dependencies of derivation '/nix/store/839m4wxg7ncn2np94s7vkm6pmja7pfn8-python3-3.9.13-env.drv' failed to build
```
This is a bit weird to me since `Cargo.lock` is present in `watchfiles` repo. But at this point, I'm shooting blank and just trying to see what works.

</details>

**Comment by sciyoshi** [comment]
I ran into a similar issue - the watchfiles tarball released on pypi doesn't include Cargo.lock, although the source tarballs on the GitHub releases do. Here's what worked for me in the overlay:

```
watchfiles = super.watchfiles.overridePythonAttrs (
  old: rec {
    src = pkgs.fetchFromGitHub {
      owner = "samuelcolvin";
      repo = "watchfiles";
      rev = "v${old.version}";
      sha256 = "sha256-Cm0FNyfVvlMjNxnVnl/Fl0f/RLnhv9a0aEJLk9l/Rus=";
    };
    cargoDeps = pkgs.rustPlatform.fetchCargoTarball {
      inherit src;
      name = "${old.pname}-${old.version}";
      hash = "sha256-nIYoLSDTZ+ahVqQwkfjivrGFdkcBpr8kpT3I29olL9E=";
    };
    nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ [
      pkgs.rustPlatform.cargoSetupHook
      pkgs.rustPlatform.maturinBuildHook
    ];
  }
);
```

You would need to replace the hashes according to the version you're using. Would be nice to get this upstreamed.
