### ISSUE TITLE
Error while trying to build mypy in mkPoetryEnv

### ISSUE THREAD

**Issue by thiagokokada** [nix-community/poetry2nix#91]
I am trying `poetry2nix.mkPoetryEnv` from current release 20.03. This is the script:
```nix
with import <nixpkgs> {};

let pythonEnv = poetry2nix.mkPoetryEnv {
  projectDir = ./.;
};
in
mkShell {
  name = "i3pyblocks";
  nativeBuildInputs = [
    libffi
    libpulseaudio
    pythonEnv
  ];
  LD_LIBRARY_PATH="${libpulseaudio}/lib";
}
```

Using this `poetry.lock` file: https://github.com/thiagokokada/i3pyblocks/blob/master/poetry.lock, but `mypy` fails to build:

```
these derivations will be built:
  /nix/store/5g359s0lhlb4r8zw5gn4wvxi8hs0mwxf-python3.7-pytest-mypy-0.6.1.drv
  /nix/store/r0l62blqj2l6f12l00y2dhavs3sbkrrc-python3-3.7.6-env.drv
building '/nix/store/5g359s0lhlb4r8zw5gn4wvxi8hs0mwxf-python3.7-pytest-mypy-0.6.1.drv'...
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Using setuptoolsShellHook
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
unpacking sources
unpacking source archive /nix/store/c7fgq14pwgac3w2mlxq0mjagkfnzs5bw-pytest-mypy-0.6.1.tar.gz
source root is pytest-mypy-0.6.1
setting SOURCE_DATE_EPOCH to timestamp 1586043272 of file pytest-mypy-0.6.1/setup.cfg
patching sources
configuring
no configure script, doing nothing
building
Executing setuptoolsBuildPhase
WARNING: The directory '/homeless-shelter/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5f13cd0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ea4a50>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ea4c50>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ea4e10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ea4ed0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
ERROR: Could not find a version that satisfies the requirement setuptools-scm>=3.5 (from versions: none)
ERROR: No matching distribution found for setuptools-scm>=3.5
Traceback (most recent call last):
  File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
    subprocess.check_call(cmd)
  File "/nix/store/nlgrx0cl1l87nx0w660lb3jksn9jdca9-python3-3.7.6/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/nlgrx0cl1l87nx0w660lb3jksn9jdca9-python3-3.7.6/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp8mwmgjab', '--quiet', 'setuptools-scm>=3.5']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 62, in <module>
    'mypy = pytest_mypy',
  File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
    _install_setup_requires(attrs)
  File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
    replace_conflicting=True,
  File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
    replace_conflicting=replace_conflicting
  File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
    return self.obtain(req, installer)
  File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
    return installer(requirement)
  File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
    return fetch_build_egg(self, req)
  File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
    raise DistutilsError(str(e))
distutils.errors.DistutilsError: Command '['/nix/store/nlgrx0cl1l87nx0w660lb3jksn9jdca9-python3-3.7.6/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmp8mwmgjab', '--quiet', 'setuptools-scm>=3.5']' returned non-zero exit status 1.
builder for '/nix/store/5g359s0lhlb4r8zw5gn4wvxi8hs0mwxf-python3.7-pytest-mypy-0.6.1.drv' failed with exit code 1
cannot build derivation '/nix/store/r0l62blqj2l6f12l00y2dhavs3sbkrrc-python3-3.7.6-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/r0l62blqj2l6f12l00y2dhavs3sbkrrc-python3-3.7.6-env.drv' failed
```

It seems to be trying to connect via HTTP to `/simple/setuptools-scm/`? Any idea of what could be causing this issue?

**Comment by thiagokokada** [comment]
Trying the current master:
```nix
with import <nixpkgs> {};

let src = fetchFromGitHub {
  owner = "nix-community";
  repo = "poetry2nix";
  # Commit hash for master as of 2020-01-08
  # `git ls-remote https://github.com/nix-community/poetry2nix.git master`
  rev = "8d7d705aa070ebc615cfc73215f840bac24fffb3";
  sha256 = "1y4s92q4xa88jz5im6pwz0r713rxhvglsgyddgkkrg8xrd9rrajn";
};
in

with import "${src.out}/overlay.nix" pkgs pkgs;

let pythonEnv = poetry2nix.mkPoetryEnv {
  projectDir = ./.;
};
in
mkShell {
  name = "i3pyblocks";
  nativeBuildInputs = [
    libffi
    libpulseaudio
    pythonEnv
  ];
  LD_LIBRARY_PATH="${libpulseaudio}/lib";
}
```

```
these derivations will be built:
  /nix/store/lk7arq1n6kxghqh4wbiljpn1blgpgl4n-python3.7-pytest-mypy-0.6.1.drv  /nix/store/j0vw3c9ibsqpim5jpswbwfi5ps6q1913-python3-3.7.6-env.drv
building '/nix/store/lk7arq1n6kxghqh4wbiljpn1blgpgl4n-python3.7-pytest-mypy-0.6.1.drv'...
Sourcing python-catch-conflicts-hook.shSourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-build-hook
Using pipBuildPhaseUsing pipShellHook
Sourcing pip-install-hook
Using pipInstallPhaseSourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
unpacking sourcesunpacking source archive /nix/store/c7fgq14pwgac3w2mlxq0mjagkfnzs5bw-pytest-mypy-0.6.1.tar.gz
source root is pytest-mypy-0.6.1
setting SOURCE_DATE_EPOCH to timestamp 1586043272 of file pytest-mypy-0.6.1/setup.cfgpatching sources
configuring
no configure script, doing nothingbuilding
Executing pipBuildPhase
Removing pyproject.toml...Creating a wheel...
WARNING: The directory '/homeless-shelter/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.Processing /build/pytest-mypy-0.6.1    ERROR: Command errored out with exit status 1:
     command: /nix/store/nlgrx0cl1l87nx0w660lb3jksn9jdca9-python3-3.7.6/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/build/pip-req-build-7e4b840d/setup.py'"'"'; __file__='"'"'/build/pip-req-build-7e4b840d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /build/pip-req-build-7e4b840d/pip-egg-info
         cwd: /build/pip-req-build-7e4b840d/
    Complete output (38 lines):
    WARNING: The directory '/homeless-shelter/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5f14bd0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ea5a10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ea5c10>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ea5dd0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5ea5e90>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/setuptools-scm/
    ERROR: Could not find a version that satisfies the requirement setuptools-scm>=3.5 (from versions: none)
    ERROR: No matching distribution found for setuptools-scm>=3.5
    Traceback (most recent call last):
      File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/installer.py", line 128, in fetch_build_egg
        subprocess.check_call(cmd)
      File "/nix/store/nlgrx0cl1l87nx0w660lb3jksn9jdca9-python3-3.7.6/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/nix/store/nlgrx0cl1l87nx0w660lb3jksn9jdca9-python3-3.7.6/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmps41u9vce', '--quiet', 'setuptools-scm>=3.5']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/build/pip-req-build-7e4b840d/setup.py", line 62, in <module>
        'mypy = pytest_mypy',
      File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/dist.py", line 721, in fetch_build_eggs
        replace_conflicting=True,
      File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/dist.py", line 777, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "/nix/store/rn2rrpk56cxqi0js12qcf336fgh342yf-python3.7-setuptools-44.0.0/lib/python3.7/site-packages/setuptools/installer.py", line 130, in fetch_build_egg
        raise DistutilsError(str(e))
    distutils.errors.DistutilsError: Command '['/nix/store/nlgrx0cl1l87nx0w660lb3jksn9jdca9-python3-3.7.6/bin/python3.7', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/build/tmps41u9vce', '--quiet', 'setuptools-scm>=3.5']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
builder for '/nix/store/lk7arq1n6kxghqh4wbiljpn1blgpgl4n-python3.7-pytest-mypy-0.6.1.drv' failed with exit code 1
cannot build derivation '/nix/store/j0vw3c9ibsqpim5jpswbwfi5ps6q1913-python3-3.7.6-env.drv': 1 dependencies couldn't be built
error: build of '/nix/store/j0vw3c9ibsqpim5jpswbwfi5ps6q1913-python3-3.7.6-env.drv' failed
```

The error is different, but the issue seems the same.

**Comment by adisbladis** [comment]
Poetry doesn't include all _build time_ dependencies in it's lock file.
`setuptools-scm` is picked from Nixpkgs in case it's not found in the lock and the version picked is too old.

Try adding an explicit dependency on `setuptools-scm` in your project by `poetry add --dev setuptools-scm` so you can manage the version of it yourself instead of relying on nixpkgs for it.

**Comment by thiagokokada** [comment]
Adding `setuptools-scm` to my project worked.
