### ISSUE TITLE
Vispy fails to build

### ISSUE THREAD

**Issue by mjlbach** [nix-community/poetry2nix#99]
Played around with a couple overrides to get this to build, but no luck thus far

shell.nix
```
with import <nixpkgs> { };
let
  src = fetchFromGitHub {
    owner = "nix-community";
    repo = "poetry2nix";
    rev = "98df940936e09164fdf30f3348fc071403667074";
    sha256 = "163d72djp5z6459v964ij2qam4p2zw6xfjfh3b94qz8xyi2c3w15";
  };
in
with import "${src.out}/overlay.nix" pkgs pkgs;
let
  pythonEnv = poetry2nix.mkPoetryEnv {
    projectDir = ./.;
    python = python3;
    pyproject = ./pyproject.toml;
    poetrylock = ./poetry.lock;
    # preferWheels = true;
    overrides = poetry2nix.overrides.withDefaults
      (
        self: super: {
          vispy = super.vispy.overrideAttrs
            (
              old: {
                nativeBuildInputs = old.nativeBuildInputs ++ [
                  self.cython
                ];
              }
            );
        }
      );
  };
in
mkShell {
  name = "vispy-environment";

  nativeBuildInputs = [
    pythonEnv
  ];

}
```
pyproject.toml
```
[tool.poetry]
name = "vispy_env"
version = "0.1.0"
description = ""
authors = ["Michael Lingelbach <m.j.lbach@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pyqt5 = "^5.14.1"
sip = "^5.1.0"
numpy = "^1.18.4"
vispy = "^0.6.4"
setuptools-scm = { version = "^3.4", extras = ["toml"] }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Log output
``` log
May 07 01:41:42.676 INFO build message, message: BuildEvent(Failure { nix_file: Shell("/home/mjlbach/Repositories/new/shell.nix failure: Exit { cmd: "\"nix-build\" \"--out-link\" \"/tmp/.tmp91FkWU/result\" \"--\" \"/tmp/.tmp5GzvYF/result\"", status: Some(100), logs: [
these derivations will be built: 
  /nix/store/amr8h2ab0rw60ac5z52k3i0q8jvk1dl1-python3.7-vispy-0.6.4.drv 
  /nix/store/3bb71502qq91fjw1al6vkryf13fz487j-python3-3.7.7-env.drv 
  /nix/store/awrnlsk2ww5ycc6a7230s87hxmk91dma-lorri-wrapped-project-vispy-environment.drv 
building \'/nix/store/amr8h2ab0rw60ac5z52k3i0q8jvk1dl1-python3.7-vispy-0.6.4.drv\'... 
Sourcing python-remove-tests-dir-hook 
Sourcing python-catch-conflicts-hook.sh 
Sourcing python-remove-bin-bytecode-hook.sh 
Sourcing pip-build-hook 
Using pipBuildPhase 
Using pipShellHook 
Sourcing pip-install-hook 
Using pipInstallPhase 
Sourcing python-imports-check-hook.sh 
Using pythonImportsCheckPhase 
Sourcing python-namespaces-hook 
unpacking sources 
unpacking source archive /nix/store/jf28zwlwhwm61hpqkjhksxyywk0whwis-vispy-0.6.4.tar.gz 
source root is vispy-0.6.4 
setting SOURCE_DATE_EPOCH to timestamp 1576277701 of file vispy-0.6.4/setup.cfg 
patching sources 
configuring 
no configure script, doing nothing 
building 
Executing pipBuildPhase 
Removing pyproject.toml... 
Creating a wheel... 
WARNING: The directory \'/homeless-shelter/.cache/pip\' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo\'s -H flag. 
Processing /build/vispy-0.6.4 
    ERROR: Command errored out with exit status 1: 
     command: /nix/store/ihy2vly61ndky6qlv1q4dfdiv28vszkh-python3-3.7.7/bin/python3.7 -c \'import sys, setuptools, tokenize; sys.argv[0] = \'\"\'\"\'/build/pip-req-build-a_nklnxc/setup.py\'\"\'\"\'; __file__=\'\"\'\"\'/build/pip-req-build-a_nklnxc/setup.py\'\"\'\"\';f=getattr(tokenize, \'\"\'\"\'open\'\"\'\"\', open)(__file__);code=f.read().replace(\'\"\'\"\'\\r\\n\'\"\'\"\', \'\"\'\"\'\\n\'\"\'\"\');f.close();exec(compile(code, __file__, \'\"\'\"\'exec\'\"\'\"\'))\' egg_info --egg-base /build/pip-req-build-a_nklnxc/pip-egg-info 
         cwd: /build/pip-req-build-a_nklnxc/ 
    Complete output (44 lines): 
    setup.py entered 
    $PATH=/nix/store/ihy2vly61ndky6qlv1q4dfdiv28vszkh-python3-3.7.7/bin:/nix/store/wqrpi0di1jb17gmzim8j58rznz4v6wqf-python3.7-setuptools-45.2.0/bin:/nix/store/ihy2vly61ndky6qlv1q4dfdiv28vszkh-python3-3.7.7/bin:/nix/store/cmdsjcd6irzinnrwg620j0s1vzd2y11q-python3.7-pip-20.0.2/bin:/nix/store/dagvc52hnmmfan7lrhs4pxy9jkw9yjqv-python3.7-wheel-0.33.6/bin:/nix/store/zxwvlpx592ivikrvkgzn1ml8y5vsb1kh-python3.7-Cython-0.29.14/bin:/nix/store/sicn6b10ixbs6435d7dr630i2hxphfpr-patchelf-0.9/bin:/nix/store/k930l9lckxjf4zmafv4aapvdbd2sibmj-gcc-wrapper-9.3.0/bin:/nix/store/52x4908vr922dhnxz1i5rfnrsq244vzc-gcc-9.3.0/bin:/nix/store/g5lavnivfasac7m15g3mh9lhmhsr5vl4-glibc-2.30-bin/bin:/nix/store/ca9mkrf8sa8md8pv61jslhcnfk9mmg4p-coreutils-8.31/bin:/nix/store/3gd7zz0s80k50amwzj3015ddz0sd9inl-binutils-wrapper-2.31.1/bin:/nix/store/3b3ighb83nhifa1v4n7855hlbdl1mhf9-binutils-2.31.1/bin:/nix/store/g5lavnivfasac7m15g3mh9lhmhsr5vl4-glibc-2.30-bin/bin:/nix/store/ca9mkrf8sa8md8pv61jslhcnfk9mmg4p-coreutils-8.31/bin:/nix/store/ca9mkrf8sa8md8pv61jslhcnfk9mmg4p-coreutils-8.31/bin:/nix/store/hg3albf7g05ljfqrfjhd58rblimrp6ph-findutils-4.7.0/bin:/nix/store/k7rakfl1ld9ycfm1zzszly0161h6jlcp-diffutils-3.7/bin:/nix/store/jpqlmf3wqg281j8fdz50kjl525pfsxjc-gnused-4.8/bin:/nix/store/8pajzfyqx1v7dz1znrnrc4pqj5rmnx24-gnugrep-3.4/bin:/nix/store/miwvn81sgbbcq5bfglr6v3pwchgsd00c-gawk-5.0.1/bin:/nix/store/0s93dpvxn7vaaah3n1lgz0q0xqdfsbkj-gnutar-1.32/bin:/nix/store/6yqb5dfmlsx0zr0q8xzi8v4wbrzmvwpf-gzip-1.10/bin:/nix/store/hgp00a1rgwqxjcrkqhbjrfb5df7wjhl5-bzip2-1.0.6.0.1-bin/bin:/nix/store/998ykzc5mazwak08hxayqmyqkyz18fcb-gnumake-4.2.1/bin:/nix/store/kgp3vq8l9yb8mzghbw83kyr3f26yqvsz-bash-4.4-p23/bin:/nix/store/c8nzpy2f2sz0w3mp4x8gkpn4hd4l2420-patch-2.7.6/bin:/nix/store/6ca524vb3yg59ag3khm0010591rny9v1-xz-5.2.5-bin/bin 
    Compiling vispy/visuals/text/_sdf_cpu.pyx because it changed. 
    [1/1] Cythonizing vispy/visuals/text/_sdf_cpu.pyx 
    WARNING: The directory \'/homeless-shelter/.cache/pip\' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo\'s -H flag. 
    WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by \'NewConnectionError(\'<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5f26c10>: Failed to establish a new connection: [Errno -2] Name or service not known\')\': /simple/setuptools-scm-git-archive/ 
    WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by \'NewConnectionError(\'<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5e9e350>: Failed to establish a new connection: [Errno -2] Name or service not known\')\': /simple/setuptools-scm-git-archive/ 
    WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by \'NewConnectionError(\'<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5e9e4d0>: Failed to establish a new connection: [Errno -2] Name or service not known\')\': /simple/setuptools-scm-git-archive/ 
    WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by \'NewConnectionError(\'<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5e9e690>: Failed to establish a new connection: [Errno -2] Name or service not known\')\': /simple/setuptools-scm-git-archive/ 
    WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by \'NewConnectionError(\'<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7ffff5e9e850>: Failed to establish a new connection: [Errno -2] Name or service not known\')\': /simple/setuptools-scm-git-archive/ 
    ERROR: Could not find a version that satisfies the requirement setuptools_scm_git_archive (from versions: none) 
    ERROR: No matching distribution found for setuptools_scm_git_archive 
    /nix/store/zxwvlpx592ivikrvkgzn1ml8y5vsb1kh-python3.7-Cython-0.29.14/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive \'language_level\' not set, using 2 for now (Py2). This will change in a later release! File: /build/pip-req-build-a_nklnxc/vispy/visuals/text/_sdf_cpu.pyx 
      tree = Parsing.p_module(s, pxd, full_module_name) 
    Traceback (most recent call last): 
      File \"/nix/store/wqrpi0di1jb17gmzim8j58rznz4v6wqf-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/installer.py\", line 128, in fetch_build_egg 
        subprocess.check_call(cmd) 
      File \"/nix/store/ihy2vly61ndky6qlv1q4dfdiv28vszkh-python3-3.7.7/lib/python3.7/subprocess.py\", line 363, in check_call 
        raise CalledProcessError(retcode, cmd) 
    subprocess.CalledProcessError: Command \'[\'/nix/store/ihy2vly61ndky6qlv1q4dfdiv28vszkh-python3-3.7.7/bin/python3.7\', \'-m\', \'pip\', \'--disable-pip-version-check\', \'wheel\', \'--no-deps\', \'-w\', \'/build/tmpkrjicua6\', \'--quiet\', \'setuptools_scm_git_archive\']\' returned non-zero exit status 1. 
 
    During handling of the above exception, another exception occurred: 
 
    Traceback (most recent call last): 
      File \"<string>\", line 1, in <module> 
      File \"/build/pip-req-build-a_nklnxc/setup.py\", line 274, in <module> 
        \'Framework :: IPython\' 
      File \"/nix/store/wqrpi0di1jb17gmzim8j58rznz4v6wqf-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/__init__.py\", line 143, in setup 
        _install_setup_requires(attrs) 
      File \"/nix/store/wqrpi0di1jb17gmzim8j58rznz4v6wqf-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/__init__.py\", line 138, in _install_setup_requires 
        dist.fetch_build_eggs(dist.setup_requires) 
      File \"/nix/store/wqrpi0di1jb17gmzim8j58rznz4v6wqf-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/dist.py\", line 721, in fetch_build_eggs 
        replace_conflicting=True, 
      File \"/nix/store/wqrpi0di1jb17gmzim8j58rznz4v6wqf-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 783, in resolve 
        replace_conflicting=replace_conflicting 
      File \"/nix/store/wqrpi0di1jb17gmzim8j58rznz4v6wqf-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 1066, in best_match 
        return self.obtain(req, installer) 
      File \"/nix/store/wqrpi0di1jb17gmzim8j58rznz4v6wqf-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 1078, in obtain 
        return installer(requirement) 
      File \"/nix/store/wqrpi0di1jb17gmzim8j58rznz4v6wqf-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/dist.py\", line 777, in fetch_build_egg 
        return fetch_build_egg(self, req) 
      File \"/nix/store/wqrpi0di1jb17gmzim8j58rznz4v6wqf-python3.7-setuptools-45.2.0/lib/python3.7/site-packages/setuptools/installer.py\", line 130, in fetch_build_egg 
        raise DistutilsError(str(e)) 
    distutils.errors.DistutilsError: Command \'[\'/nix/store/ihy2vly61ndky6qlv1q4dfdiv28vszkh-python3-3.7.7/bin/python3.7\', \'-m\', \'pip\', \'--disable-pip-version-check\', \'wheel\', \'--no-deps\', \'-w\', \'/build/tmpkrjicua6\', \'--quiet\', \'setuptools_scm_git_archive\']\' returned non-zero exit status 1. 
    ---------------------------------------- 
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. 
builder for \'/nix/store/amr8h2ab0rw60ac5z52k3i0q8jvk1dl1-python3.7-vispy-0.6.4.drv\' failed with exit code 1 
cannot build derivation \'/nix/store/3bb71502qq91fjw1al6vkryf13fz487j-python3-3.7.7-env.drv\': 1 dependencies couldn\'t be built 
cannot build derivation \'/nix/store/awrnlsk2ww5ycc6a7230s87hxmk91dma-lorri-wrapped-project-vispy-environment.drv\': 1 dependencies couldn\'t be built 
error: build of \'/nix/store/awrnlsk2ww5ycc6a7230s87hxmk91dma-lorri-wrapped-project-vispy-environment.drv\' failed")] } }), expr: /home/mjlbach/Repositories/new/shell.nix

```

**Comment by adisbladis** [comment]
Try adding `setuptools-scm-git-archive` in the override:
``` nix


with import <nixpkgs> { };
let
  src = fetchFromGitHub {
    owner = "nix-community";
    repo = "poetry2nix";
    rev = "98df940936e09164fdf30f3348fc071403667074";
    sha256 = "163d72djp5z6459v964ij2qam4p2zw6xfjfh3b94qz8xyi2c3w15";
  };
in
with import "${src.out}/overlay.nix" pkgs pkgs;
let
  pythonEnv = poetry2nix.mkPoetryEnv {
    projectDir = ./.;
    python = python3;
    pyproject = ./pyproject.toml;
    poetrylock = ./poetry.lock;
    # preferWheels = true;
    overrides = poetry2nix.overrides.withDefaults
      (
        self: super: {
          vispy = super.vispy.overrideAttrs
            (
              old: {
                nativeBuildInputs = old.nativeBuildInputs ++ [
                  self.cython
                  self.setuptools-scm-git-archive
                ];
              }
            );
        }
      );
  };
in
mkShell {
  name = "vispy-environment";

  nativeBuildInputs = [
    pythonEnv
  ];

}
```

**Comment by mjlbach** [comment]
Thank you! That seems to resolve the build issue... I'm getting an import error now though.

```
❯ python
Python 3.7.7 (default, Mar 10 2020, 06:34:06)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vispy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/yli0nrgjay785a6l0lypbv3lhxm27j57-python3-3.7.7-env/lib/python3.7/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/nix/store/yli0nrgjay785a6l0lypbv3lhxm27j57-python3-3.7.7-env/lib/python3.7/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/nix/store/yli0nrgjay785a6l0lypbv3lhxm27j57-python3-3.7.7-env/lib/python3.7/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/nix/store/yli0nrgjay785a6l0lypbv3lhxm27j57-python3-3.7.7-env/lib/python3.7/site-packages/vispy/util/fonts/_triage.py", line 11, in <module>
    from ._freetype import _load_glyph
  File "/nix/store/yli0nrgjay785a6l0lypbv3lhxm27j57-python3-3.7.7-env/lib/python3.7/site-packages/vispy/util/fonts/_freetype.py", line 16, in <module>
    from ...ext.fontconfig import find_font
  File "/nix/store/yli0nrgjay785a6l0lypbv3lhxm27j57-python3-3.7.7-env/lib/python3.7/site-packages/vispy/ext/fontconfig.py", line 12, in <module>
    raise ImportError('fontconfig not found')
ImportError: fontconfig not found
>>>
```

**Comment by mjlbach** [comment]
Maybe related https://github.com/NixOS/nixpkgs/pull/79235/files

**Comment by adisbladis** [comment]
Seems very likely, maybe try this:
``` nix
    overrides = poetry2nix.overrides.withDefaults
      (
        self: super: {
          vispy = super.vispy.overrideAttrs
            (
              old: {
                inherit (pkgs.python3.pkgs.vispy) patches;  # Note this line in particular
                nativeBuildInputs = old.nativeBuildInputs ++ [
                  self.cython
                  self.setuptools-scm-git-archive  # Note: only diff is this line 
                ];
              }
            );
        }
      );
```
